--
-- Script was generated by Devart dbForge Studio for PostgreSQL, Version 3.1.839.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 24/07/2024 10:25:54
-- Server version: 14.10
--

INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(149, 118, 77, '2024-06-12 15:08:53', '2024-06-12 15:08:53');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(150, 119, 78, '2024-06-12 15:09:03', '2024-06-12 15:09:03');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(151, 117, 73, '2024-06-12 15:09:16', '2024-06-12 15:09:16');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(152, 116, 6, '2024-06-12 15:09:34', '2024-06-12 15:09:34');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(153, 115, 1, '2024-06-12 15:09:46', '2024-06-12 15:09:46');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(154, 114, 77, '2024-06-12 15:10:20', '2024-06-12 15:10:20');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(155, 113, 73, '2024-06-12 15:10:36', '2024-06-12 15:10:36');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(156, 112, 40, '2024-06-12 15:10:47', '2024-06-12 15:10:47');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(157, 111, 6, '2024-06-12 15:10:59', '2024-06-12 15:10:59');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(158, 110, 5, '2024-06-12 15:11:09', '2024-06-12 15:11:09');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(159, 109, 1, '2024-06-12 15:11:20', '2024-06-12 15:11:20');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(160, 108, 3, '2024-06-12 15:11:32', '2024-06-12 15:11:32');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(161, 107, 2, '2024-06-12 15:11:56', '2024-06-12 15:11:56');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(162, 106, 77, '2024-06-12 15:12:34', '2024-06-12 15:12:34');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(163, 105, 73, '2024-06-12 15:13:05', '2024-06-12 15:13:05');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(164, 104, 6, '2024-06-12 15:13:14', '2024-06-12 15:13:14');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(165, 103, 1, '2024-06-12 15:13:23', '2024-06-12 15:13:23');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(166, 102, 77, '2024-06-12 15:13:48', '2024-06-12 15:13:48');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(167, 101, 73, '2024-06-12 15:13:58', '2024-06-12 15:13:58');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(168, 100, 6, '2024-06-12 15:14:08', '2024-06-12 15:14:08');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(169, 99, 1, '2024-06-12 15:14:18', '2024-06-12 15:14:18');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(170, 98, 77, '2024-06-12 15:14:49', '2024-06-12 15:14:49');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(171, 97, 73, '2024-06-12 15:14:56', '2024-06-12 15:14:56');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(172, 96, 6, '2024-06-12 15:15:04', '2024-06-12 15:15:04');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(173, 95, 5, '2024-06-12 15:15:12', '2024-06-12 15:15:12');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(174, 94, 1, '2024-06-12 15:15:20', '2024-06-12 15:15:20');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(175, 93, 3, '2024-06-12 15:15:30', '2024-06-12 15:15:30');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(176, 92, 77, '2024-06-12 15:15:50', '2024-06-12 15:15:50');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(177, 91, 73, '2024-06-12 15:15:59', '2024-06-12 15:15:59');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(178, 90, 6, '2024-06-12 15:16:07', '2024-06-12 15:16:07');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(179, 89, 1, '2024-06-12 15:16:15', '2024-06-12 15:16:15');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(180, 88, 73, '2024-06-12 15:16:47', '2024-06-12 15:16:47');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(181, 87, 6, '2024-06-12 15:16:56', '2024-06-12 15:16:56');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(182, 86, 1, '2024-06-12 15:17:04', '2024-06-12 15:17:04');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(183, 120, 2, '2024-06-12 15:17:34', '2024-06-12 15:17:34');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(184, 121, 3, '2024-06-12 15:17:43', '2024-06-12 15:17:43');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(185, 122, 1, '2024-06-12 15:17:53', '2024-06-12 15:17:53');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(186, 123, 6, '2024-06-12 15:18:00', '2024-06-12 15:18:00');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(187, 124, 73, '2024-06-12 15:18:08', '2024-06-12 15:18:08');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(188, 125, 77, '2024-06-12 15:18:26', '2024-06-12 15:18:26');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(189, 126, 1, '2024-06-12 15:18:35', '2024-06-12 15:18:35');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(190, 127, 6, '2024-06-12 15:18:42', '2024-06-12 15:18:42');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(191, 128, 73, '2024-06-12 15:18:51', '2024-06-12 15:18:51');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(192, 129, 91, '2024-06-12 15:19:49', '2024-06-12 15:19:49');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(193, 130, 78, '2024-06-12 15:20:16', '2024-06-12 15:20:16');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(194, 131, 77, '2024-06-12 15:20:38', '2024-06-12 15:20:38');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(195, 132, 1, '2024-06-12 15:21:24', '2024-06-12 15:21:24');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(196, 133, 6, '2024-06-12 15:21:43', '2024-06-12 15:21:43');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(197, 134, 73, '2024-06-12 15:22:04', '2024-06-12 15:22:04');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(198, 135, 91, '2024-06-12 15:22:20', '2024-06-12 15:22:20');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(199, 136, 78, '2024-06-12 15:22:35', '2024-06-12 15:22:35');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(200, 137, 77, '2024-06-12 15:22:54', '2024-06-12 15:22:54');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(201, 138, 3, '2024-06-12 15:24:32', '2024-06-12 15:24:32');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(202, 139, 1, '2024-06-12 15:24:47', '2024-06-12 15:24:47');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(203, 140, 5, '2024-06-12 15:25:05', '2024-06-12 15:25:05');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(204, 141, 6, '2024-06-12 15:25:19', '2024-06-12 15:25:19');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(205, 142, 73, '2024-06-12 15:25:37', '2024-06-12 15:25:37');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(207, 144, 77, '2024-06-12 15:26:29', '2024-06-12 15:26:29');
INSERT INTO demo_winter_erp.public.produk_layanan_bandwidth(id, layanan_id, bandwidth_id, created_at, updated_at) VALUES
(208, 143, 77, '2024-06-13 14:02:39', '2024-06-13 14:02:39');