--
-- Script was generated by Devart dbForge Studio for PostgreSQL, Version 3.1.839.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 24/07/2024 10:25:33
-- Server version: 14.10
--

INSERT INTO demo_winter_erp.public.bantuan_pelanggan_kategori(id, name, created_at, updated_at) VALUES
(4, E'Request', '2024-01-15 03:12:52', '2024-01-15 03:12:52');
INSERT INTO demo_winter_erp.public.bantuan_pelanggan_kategori(id, name, created_at, updated_at) VALUES
(5, E'Information', '2024-01-15 03:12:58', '2024-01-15 03:12:58');
INSERT INTO demo_winter_erp.public.bantuan_pelanggan_kategori(id, name, created_at, updated_at) VALUES
(6, E'Complaint', '2024-01-15 03:13:02', '2024-01-15 03:13:02');
INSERT INTO demo_winter_erp.public.bantuan_pelanggan_kategori(id, name, created_at, updated_at) VALUES
(7, E'Force Majeure', '2024-01-19 07:46:31', '2024-02-20 06:59:41');
INSERT INTO demo_winter_erp.public.bantuan_pelanggan_kategori(id, name, created_at, updated_at) VALUES
(74, E'Maintenance', '2024-04-29 14:30:08', '2024-04-29 14:30:08');
INSERT INTO demo_winter_erp.public.bantuan_pelanggan_kategori(id, name, created_at, updated_at) VALUES
(76, E'Urgent Maintenance', '2024-04-29 14:35:29', '2024-04-29 14:35:29');
INSERT INTO demo_winter_erp.public.bantuan_pelanggan_kategori(id, name, created_at, updated_at) VALUES
(79, E'Manage Service Email', '2024-04-29 15:36:01', '2024-04-29 15:36:01');