--
-- Script was generated by Devart dbForge Studio for PostgreSQL, Version 3.1.839.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 24/07/2024 10:25:59
-- Server version: 14.10
--

INSERT INTO demo_winter_erp.public.subjek_penawaran(id, subjek, created_at, updated_at, nama_tenant) VALUES
(40, E'Penawaran Local Loop', '06/02/2024 04:35:16.000000+07 AD', '2024-02-06 04:35:16', E'SMY');
INSERT INTO demo_winter_erp.public.subjek_penawaran(id, subjek, created_at, updated_at, nama_tenant) VALUES
(6, E'Penawaran SOHO', '19/01/2024 13:02:00.000000+07 AD', '2024-04-13 09:48:41', E'SMY');
INSERT INTO demo_winter_erp.public.subjek_penawaran(id, subjek, created_at, updated_at, nama_tenant) VALUES
(75, E'Ui', '15/04/2024 15:12:07.000000+07 AD', '2024-04-15 15:12:07', E'SMY');
INSERT INTO demo_winter_erp.public.subjek_penawaran(id, subjek, created_at, updated_at, nama_tenant) VALUES
(76, E'Penawaran Internet Dedicated', '30/05/2024 14:22:53.000000+07 AD', '2024-05-30 14:22:53', E'SMY');