--
-- Script was generated by Devart dbForge Studio for PostgreSQL, Version 3.1.839.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 24/07/2024 10:25:56
-- Server version: 14.10
--

INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(126, 7, E'customer-support:forward-ticket', true, '2024-04-29 05:11:56', '2024-04-29 05:11:56');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(127, 7, E'sales-prospek:input-data', true, '2024-04-29 05:11:56', '2024-04-29 05:11:56');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(128, 7, E'sales-prospek:request-soft-survey', true, '2024-04-29 05:11:56', '2024-04-29 05:11:56');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(129, 7, E'sales-prospek:input-soft-survey', true, '2024-04-29 05:11:56', '2024-04-29 05:11:56');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(130, 7, E'soft-survey:schedule-survey-onsite', true, '2024-04-29 05:11:56', '2024-04-29 05:11:56');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(131, 7, E'soft-survey:input-survey-onsite', true, '2024-04-29 05:11:56', '2024-04-29 05:11:56');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(132, 7, E'survey-onsite:schedule-instalasi', true, '2024-04-29 05:11:56', '2024-04-29 05:11:56');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(133, 7, E'survey-onsite:input-instalasi', true, '2024-04-29 05:11:56', '2024-04-29 05:11:56');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(134, 7, E'survey-onsite:schedule-aktivasi', true, '2024-04-29 05:11:56', '2024-04-29 05:11:56');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(135, 7, E'survey-onsite:input-aktivasi', true, '2024-04-29 05:11:56', '2024-04-29 05:11:56');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(136, 7, E'aktivasi-pelanggan:input-data', true, '2024-04-29 05:11:56', '2024-04-29 05:11:56');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(137, 7, E'aktivasi-pelanggan:input-pelanggan', true, '2024-04-29 05:11:56', '2024-04-29 05:11:56');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(138, 7, E'aktivasi-pelanggan:perubahan-layanan', true, '2024-04-29 05:11:56', '2024-04-29 05:11:56');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(139, 7, E'approval:approve', true, '2024-04-29 05:11:56', '2024-04-29 05:11:56');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(140, 7, E'approval:disapprove', true, '2024-04-29 05:11:56', '2024-04-29 05:11:56');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(141, 5, E'customer-support:forward-ticket', true, '2024-04-29 05:15:57', '2024-04-29 05:15:57');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(142, 5, E'trouble-ticket:send-assignment', true, '2024-04-29 05:15:57', '2024-04-29 05:15:57');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(143, 5, E'sales-prospek:input-data', true, '2024-04-29 05:15:57', '2024-04-29 05:15:57');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(144, 5, E'sales-prospek:request-soft-survey', true, '2024-04-29 05:15:57', '2024-04-29 05:15:57');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(145, 5, E'sales-prospek:input-soft-survey', true, '2024-04-29 05:15:57', '2024-04-29 05:15:57');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(146, 5, E'soft-survey:schedule-survey-onsite', true, '2024-04-29 05:15:57', '2024-04-29 05:15:57');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(147, 5, E'soft-survey:input-survey-onsite', true, '2024-04-29 05:15:57', '2024-04-29 05:15:57');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(148, 5, E'survey-onsite:schedule-instalasi', true, '2024-04-29 05:15:57', '2024-04-29 05:15:57');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(149, 5, E'survey-onsite:input-instalasi', true, '2024-04-29 05:15:57', '2024-04-29 05:15:57');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(150, 5, E'survey-onsite:schedule-aktivasi', true, '2024-04-29 05:15:57', '2024-04-29 05:15:57');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(151, 5, E'survey-onsite:input-aktivasi', true, '2024-04-29 05:15:57', '2024-04-29 05:15:57');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(152, 5, E'approval:approve', true, '2024-04-29 05:15:57', '2024-04-29 05:15:57');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(153, 5, E'approval:disapprove', true, '2024-04-29 05:15:57', '2024-04-29 05:15:57');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(30, 2, E'aktifitas-sales:input-data', true, '2024-03-28 10:57:47', '2024-03-28 10:57:47');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(55, 4, E'aktifitas-sales:input-data', true, '2024-04-13 09:43:31', '2024-04-13 09:43:31');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(171, 41, E'aktifitas-sales:input-data', true, '2024-06-21 10:12:06', '2024-06-21 10:12:06');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(172, 41, E'customer-support:forward-ticket', true, '2024-06-21 10:12:06', '2024-06-21 10:12:06');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(173, 41, E'trouble-ticket:send-assignment', true, '2024-06-21 10:12:06', '2024-06-21 10:12:06');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(174, 41, E'sales-prospek:input-data', true, '2024-06-21 10:12:06', '2024-06-21 10:12:06');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(175, 41, E'sales-prospek:request-soft-survey', true, '2024-06-21 10:12:06', '2024-06-21 10:12:06');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(176, 41, E'sales-prospek:input-soft-survey', true, '2024-06-21 10:12:06', '2024-06-21 10:12:06');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(177, 41, E'soft-survey:schedule-survey-onsite', true, '2024-06-21 10:12:06', '2024-06-21 10:12:06');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(178, 41, E'soft-survey:input-survey-onsite', true, '2024-06-21 10:12:06', '2024-06-21 10:12:06');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(179, 41, E'survey-onsite:schedule-instalasi', true, '2024-06-21 10:12:06', '2024-06-21 10:12:06');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(180, 41, E'survey-onsite:input-instalasi', true, '2024-06-21 10:12:06', '2024-06-21 10:12:06');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(181, 41, E'survey-onsite:schedule-aktivasi', true, '2024-06-21 10:12:06', '2024-06-21 10:12:06');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(182, 41, E'survey-onsite:input-aktivasi', true, '2024-06-21 10:12:06', '2024-06-21 10:12:06');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(183, 41, E'aktivasi-pelanggan:input-data', true, '2024-06-21 10:12:06', '2024-06-21 10:12:06');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(184, 41, E'aktivasi-pelanggan:input-pelanggan', true, '2024-06-21 10:12:06', '2024-06-21 10:12:06');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(185, 41, E'aktivasi-pelanggan:perubahan-layanan', true, '2024-06-21 10:12:06', '2024-06-21 10:12:06');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(186, 41, E'approval:approve', true, '2024-06-21 10:12:06', '2024-06-21 10:12:06');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(187, 41, E'approval:disapprove', true, '2024-06-21 10:12:06', '2024-06-21 10:12:06');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(188, 3, E'trouble-ticket:send-assignment', true, '2024-07-02 10:50:48', '2024-07-02 10:50:48');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(189, 3, E'sales-prospek:request-soft-survey', true, '2024-07-02 10:50:48', '2024-07-02 10:50:48');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(190, 3, E'soft-survey:schedule-survey-onsite', true, '2024-07-02 10:50:48', '2024-07-02 10:50:48');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(191, 3, E'survey-onsite:schedule-instalasi', true, '2024-07-02 10:50:48', '2024-07-02 10:50:48');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(192, 3, E'survey-onsite:schedule-aktivasi', true, '2024-07-02 10:50:48', '2024-07-02 10:50:48');
INSERT INTO demo_winter_erp.public.role_notifications(id, role_id, notification_code, is_notify, created_at, updated_at) VALUES
(193, 3, E'approval:approve', true, '2024-07-02 10:50:48', '2024-07-02 10:50:48');