--
-- Script was generated by Devart dbForge Studio for PostgreSQL, Version 3.1.839.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 24/07/2024 10:25:58
-- Server version: 14.10
--

INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(2, E'crm', E'Produk', E'manajemen-produk', NULL, 0, '2024-03-06 13:07:06', '2024-03-06 13:07:06');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(3, E'crm', E'Kategori Produk', E'manajemen-produk', E'?tab=kategori-produk', 2, '2024-03-06 13:07:06', '2024-03-06 13:07:06');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(4, E'crm', E'Produk', E'manajemen-produk', E'?tab=produk', 2, '2024-03-06 13:07:10', '2024-03-06 13:07:10');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(5, E'crm', E'Layanan', E'manajemen-produk', E'?tab=layanan', 2, '2024-03-06 13:07:14', '2024-03-06 13:07:14');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(6, E'crm', E'Aktifitas Harian Sales', E'manajemen-sales', NULL, 0, '2024-03-06 13:07:18', '2024-03-06 13:07:18');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(7, E'crm', E'Customer Support', E'bantuan-pelanggan', NULL, 0, '2024-03-06 13:07:21', '2024-03-06 13:07:21');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(8, E'crm', E'Tiket', E'bantuan-pelanggan', E'?tab=tiket', 7, '2024-03-06 13:07:22', '2024-03-06 13:07:22');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(9, E'crm', E'Tiket Terkirim ke Teknis', E'bantuan-pelanggan', E'?tab=tiket-terkirim', 7, '2024-03-06 13:07:26', '2024-03-06 13:07:26');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(10, E'crm', E'Trouble Ticket', E'bantuan-pelanggan-trouble', NULL, 0, '2024-03-06 13:07:29', '2024-03-06 13:07:29');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(11, E'crm', E'Tiket', E'bantuan-pelanggan-trouble', E'?tab=tiket', 10, '2024-03-06 13:07:30', '2024-03-06 13:07:30');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(12, E'crm', E'Tiket Dari CS', E'bantuan-pelanggan-trouble', E'?tab=tiket-cs', 10, '2024-03-06 13:07:34', '2024-03-06 13:07:34');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(14, E'project', E'Soft Survey List', E'softsurveys', NULL, 0, '2024-03-06 13:07:43', '2024-03-06 13:07:43');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(15, E'project', E'List Soft Survey', E'softsurveys', E'?tab=soft-survey', 14, '2024-03-06 13:07:44', '2024-03-06 13:07:44');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(16, E'project', E'Jadwal Survey Onsite', E'softsurveys', E'?tab=jadwal-survey-onsite', 14, '2024-03-06 13:07:48', '2024-03-06 13:07:48');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(17, E'project', E'Survey Onsite List', E'surveyonsites', NULL, 0, '2024-03-06 13:07:51', '2024-03-06 13:07:51');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(18, E'project', E'List Survey Onsite', E'surveyonsites', E'?tab=survey-onsite', 17, '2024-03-06 13:07:51', '2024-03-06 13:07:51');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(19, E'project', E'Jadwal Instalasi', E'surveyonsites', E'?tab=jadwal-instalasi', 17, '2024-03-06 13:07:54', '2024-03-06 13:07:54');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(20, E'project', E'Instalasi List', E'instalasi', NULL, 0, '2024-03-06 13:07:57', '2024-03-06 13:07:57');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(21, E'project', E'Instalasi List', E'instalasi', E'?tab=instalasi', 20, '2024-03-06 13:07:58', '2024-03-06 13:07:58');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(22, E'project', E'Jadwal Aktivasi', E'instalasi', E'?tab=jadwal-aktivasi', 20, '2024-03-06 13:08:01', '2024-03-06 13:08:01');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(23, E'project', E'Aktivasi List', E'aktivasi', NULL, 0, '2024-03-06 13:08:04', '2024-03-06 13:08:04');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(24, E'billing-ar', E'Manajemen Pelanggan', E'manajemen-pelanggan', NULL, 0, '2024-03-06 13:08:07', '2024-03-06 13:08:07');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(25, E'billing-ar', E'Pelanggan Aktivasi', E'manajemen-berlangganan-pelanggan', NULL, 0, '2024-03-06 13:08:11', '2024-03-06 13:08:11');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(26, E'billing-ar', E'Invoice Pelanggan', E'manajemen-invoice-pelanggan', NULL, 0, '2024-03-06 13:08:15', '2024-03-06 13:08:15');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(27, E'billing-ap', E'Manejemen Vendor', E'manajemen-vendor', NULL, 0, '2024-03-06 13:08:19', '2024-03-06 13:08:19');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(28, E'billing-ap', E'Vendor Aktivasi', E'manajemen-berlangganan-vendor', NULL, 0, '2024-03-06 13:08:23', '2024-03-06 13:08:23');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(29, E'keuangan', E'Master Akun', E'manajemen-akun', NULL, 0, '2024-03-06 13:08:27', '2024-03-06 13:08:27');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(30, E'laporan', E'Laporan Sales Prospek', E'laporan-sales-prospek', NULL, 0, '2024-03-06 13:08:30', '2024-03-06 13:08:30');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(31, E'users', E'User', E'manajemen-user', NULL, 0, '2024-03-06 13:08:32', '2024-03-06 13:08:32');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(32, E'users', E'Role', E'manajemen-role', NULL, 0, '2024-03-06 13:08:34', '2024-03-06 13:08:34');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(34, E'pengaturan-sistem', E'Data Master', E'data-master', NULL, 0, '2024-03-06 13:08:39', '2024-03-06 13:08:39');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(35, E'pengaturan-sistem', E'Kategori Produk', E'data-master', E'?tab=kategori-produk', 34, '2024-03-06 13:08:39', '2024-03-06 13:08:39');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(36, E'pengaturan-sistem', E'Bandwidth', E'data-master', E'?tab=bandwidth', 34, '2024-03-06 13:08:43', '2024-03-06 13:08:43');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(37, E'pengaturan-sistem', E'Biaya', E'data-master', E'?tab=biaya', 34, '2024-03-06 13:08:47', '2024-03-06 13:08:47');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(38, E'pengaturan-sistem', E'Pajak', E'data-master', E'?tab=pajak', 34, '2024-03-06 13:08:51', '2024-03-06 13:08:51');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(39, E'pengaturan-sistem', E'Subjek Penawaran', E'data-master', E'?tab=subjek-penawaran', 34, '2024-03-06 13:08:55', '2024-03-06 13:08:55');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(40, E'pengaturan-sistem', E'Alasan Penolakan', E'data-master', E'?tab=alasan-penolakan', 34, '2024-03-06 13:08:58', '2024-03-06 13:08:58');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(41, E'pengaturan-sistem', E'Jenis Tiket', E'data-master', E'?tab=jenis-tiket', 34, '2024-03-06 13:09:02', '2024-03-06 13:09:02');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(42, E'pengaturan-sistem', E'Kategori Tiket', E'data-master', E'?tab=kategori-tiket', 34, '2024-03-06 13:09:06', '2024-03-06 13:09:06');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(43, E'pengaturan-sistem', E'Lokasi', E'data-master', E'?tab=lokasi', 34, NULL, NULL);
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(44, E'pengaturan-sistem', E'List Rekening', E'data-master', E'?tab=list-rekening', 34, NULL, NULL);
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(45, E'pengaturan-sistem', E'List Perusahaan', E'data-master', E'?tab=list-perusahaan', 34, NULL, NULL);
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(13, E'project', E'Sales Prospek', E'manajemen-sales-prospek', NULL, 0, '2024-03-06 13:07:38', '2024-03-06 13:07:38');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(46, E'project', E'Approval', E'manajemen-approval', NULL, 0, '2024-03-06 13:09:06', '2024-03-06 13:09:06');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(49, E'billing-ap', E'Invoice', E'invoice-vendor', NULL, 0, NULL, NULL);
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(50, E'billing-ar', E'Invoice', E'manajemen-invoice', NULL, 0, NULL, NULL);
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(58, E'laporan', E'Laporan Pelanggan', E'laporan-pelanggan', NULL, 0, '2024-03-30 16:56:13', '2024-03-30 16:56:13');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(33, E'users', E'Logs', E'manajemen-user-logs', NULL, 0, '2024-03-06 13:08:38', '2024-03-06 13:08:38');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(59, E'users', E'Work Order', E'manajemen-wo', NULL, 0, '2024-04-04 08:07:29', '2024-05-14 13:49:57');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(60, E'project', E'Penawaran', E'penawaran', NULL, 0, '2024-05-16 08:13:26', '2024-05-16 08:13:26');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(61, E'pengaturan-sistem', E'Perangkat', E'data-master', E'?tab=perangkat', 34, '2024-06-05 16:44:08', '2024-06-05 16:44:08');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(62, E'project', E'List Perangkat', E'list-perangkat-sales-prospek', NULL, 0, '2024-07-06 15:14:22', '2024-07-06 15:14:22');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(95, E'laporan', E'Laporan Sales', E'laporan-sales', NULL, 0, '2024-07-18 10:52:29', '2024-07-18 10:52:29');
INSERT INTO demo_winter_erp.public.setting_menus(id, category_code, name, slug_menu, query_slug_menu, parent_id, created_at, updated_at) VALUES
(96, E'laporan', E'Laporan Tiket', E'laporan-ticket', NULL, 0, '2024-07-18 10:53:05', '2024-07-18 10:53:05');