--
-- Script was generated by Devart dbForge Studio for PostgreSQL, Version 3.1.839.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 24/07/2024 10:25:54
-- Server version: 14.10
--

INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(89, E'WA', 87, E'Winlight-Eco', 414616, NULL, E'41', E'41', '2024-06-11 13:12:51', '2024-06-12 15:16:15', 1170270, 2251351);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(118, E'WA', 92, E'Mitra 300', 7561943, NULL, NULL, NULL, '2024-06-12 11:51:24', '2024-06-12 15:08:53', 12500000, 22500000);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(119, E'WA', 92, E'Mitra 200', 5444166, NULL, NULL, NULL, '2024-06-12 11:52:35', '2024-06-12 15:09:03', 9000000, 14500000);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(117, E'WA', 92, E'Mitra 100', 3003653, NULL, NULL, NULL, '2024-06-12 11:50:29', '2024-06-12 15:09:16', 5000000, 11500000);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(116, E'WA', 92, E'Mitra 50', 1633386, NULL, NULL, NULL, '2024-06-12 11:50:05', '2024-06-12 15:09:34', 3000000, 6500000);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(115, E'WA', 92, E'Mitra 30', 939374, NULL, NULL, NULL, '2024-06-12 11:49:33', '2024-06-12 15:09:46', 1750000, 3500000);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(114, E'WA', 91, E'Enterprise 300', 10826520, NULL, NULL, NULL, '2024-06-11 13:59:35', '2024-06-12 15:10:20', 18200000, 27500000);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(113, E'WA', 91, E'Enterprise 100', 4305801, NULL, NULL, NULL, '2024-06-11 13:59:05', '2024-06-12 15:10:36', 6800000, 11300000);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(112, E'WA', 91, E'Enterprise 60', 2440927, NULL, NULL, NULL, '2024-06-11 13:58:34', '2024-06-12 15:10:47', 5500000, 7500000);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(111, E'WA', 91, E'Enterprise 50', 2396770, NULL, E'41', E'41', '2024-06-11 13:58:04', '2024-06-12 15:10:59', 4550000, 7000000);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(110, E'WA', 91, E'Enterprise 40', 1815321, NULL, E'41', E'41', '2024-06-11 13:57:24', '2024-06-12 15:11:09', 3650000, 5700000);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(109, E'WA', 91, E'Enterprise 30', 1592479, NULL, E'41', E'41', '2024-06-11 13:56:41', '2024-06-12 15:11:20', 2750000, 6000000);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(108, E'WA', 91, E'Enterprise 20', 1176994, NULL, E'41', E'41', '2024-06-11 13:56:12', '2024-06-12 15:11:32', 1800000, 4500000);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(107, E'WA', 91, E'Enterprise 10', 719526, NULL, E'41', E'41', '2024-06-11 13:55:50', '2024-06-12 15:11:56', 1300000, 3250000);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(106, E'WA', 90, E'Winzone-Ultimate', 3309813, NULL, E'41', E'41', '2024-06-11 13:52:41', '2024-06-12 15:12:34', 5404505, 8557658);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(105, E'WA', 90, E'Winzone-Pro', 1271912, NULL, E'41', E'41', '2024-06-11 13:52:14', '2024-06-12 15:13:05', 2071171, 5854955);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(104, E'WA', 90, E'Winzone-Standard', 723738, NULL, E'41', E'41', '2024-06-11 13:51:51', '2024-06-12 15:13:14', 1170270, 3422523);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(103, E'WA', 90, E'Winzone-Eco', 481406, NULL, E'41', E'41', '2024-06-11 13:51:21', '2024-06-12 15:13:23', 809910, 2701802);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(102, E'WA', 89, E'Winlife-Ultimate', 2491739, NULL, E'41', E'41', '2024-06-11 13:25:02', '2024-06-12 15:13:48', 5854955, 9008108);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(101, E'WA', 89, E'Winlife-Pro', 1047946, NULL, E'41', E'41', '2024-06-11 13:24:35', '2024-06-12 15:13:58', 2341441, 4954054);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(100, E'WA', 89, E'Winlife-Standard', 524957, NULL, E'41', E'41', '2024-06-11 13:23:55', '2024-06-12 15:14:08', 1260360, 2881982);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(99, E'WA', 89, E'Winlife-Eco', 353837, NULL, E'41', E'41', '2024-06-11 13:22:25', '2024-06-12 15:14:18', 900000, 1981081);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(98, E'WA', 88, E'Starlife 300', 1682018, NULL, E'41', E'41', '2024-06-11 13:21:09', '2024-06-12 15:14:49', 2071171, 3872973);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(97, E'WA', 88, E'Starlife 100', 720639, NULL, E'41', E'41', '2024-06-11 13:20:44', '2024-06-12 15:14:56', 1170270, 1800901);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(96, E'WA', 88, E'Starlife 50', 354325, NULL, E'41', E'41', '2024-06-11 13:20:11', '2024-06-12 15:15:04', 701802, 1170270);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(95, E'WA', 88, E'Starlife 40', 256817, NULL, E'41', E'41', '2024-06-11 13:19:36', '2024-06-12 15:15:12', 494595, 900000);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(94, E'WA', 88, E'Starlife 30', 242523, NULL, E'41', E'41', '2024-06-11 13:18:17', '2024-06-12 15:15:20', 449550, 854955);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(93, E'WA', 88, E'Starlife 20', 185205, NULL, E'41', E'41', '2024-06-11 13:17:18', '2024-06-12 15:15:30', 341441, 764865);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(92, E'WA', 87, E'Winlight-Ultimate', 2820906, NULL, E'41', E'41', '2024-06-11 13:16:12', '2024-06-12 15:15:50', 5404505, 9458559);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(91, E'WA', 87, E'Winlight-Pro', 1220498, NULL, E'41', E'41', '2024-06-11 13:15:10', '2024-06-12 15:15:59', 2701802, 5404505);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(90, E'WA', 87, E'Winlight-Standard', 597899, NULL, E'41', E'41', '2024-06-11 13:13:56', '2024-06-12 15:16:07', 1530631, 3152252);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(88, E'WA', 86, E'Winbiz-Pro', 970036, NULL, E'41', E'41', '2024-06-11 12:57:45', '2024-06-12 15:16:47', 1530631, 2701802);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(87, E'WA', 86, E'Winbiz-Standard', 483524, NULL, E'41', E'41', '2024-06-11 12:56:45', '2024-06-12 15:16:56', 854955, 1800901);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(86, E'WA', 86, E'Winbiz-Eco', 259344, NULL, E'41', E'41', '2024-06-11 12:55:01', '2024-06-12 15:17:04', 539640, 1170270);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(120, E'SMY', 93, E'Velocity Basic 10', 91048, NULL, NULL, NULL, '2024-06-12 11:54:23', '2024-06-12 15:17:34', 125225, 179279);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(121, E'SMY', 93, E'Velocity Basic 20', 141922, NULL, NULL, NULL, '2024-06-12 11:54:42', '2024-06-12 15:17:43', 179279, 251351);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(122, E'SMY', 94, E'Velocity Lux Blue 30', 167726, NULL, NULL, NULL, '2024-06-12 11:55:07', '2024-06-12 15:17:53', 260360, 359459);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(123, E'SMY', 94, E'Velocity Lux Silver 50', 237973, NULL, NULL, NULL, '2024-06-12 11:55:25', '2024-06-12 15:18:00', 368468, 494595);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(124, E'SMY', 94, E'Velocity Lux Gold  100', 407920, NULL, NULL, NULL, '2024-06-12 11:55:45', '2024-06-12 15:18:08', 629730, 809910);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(125, E'SMY', 94, E'Velocity Lux Platinum 300', 900906, NULL, NULL, NULL, '2024-06-12 11:56:18', '2024-06-12 15:18:26', 1260360, 1710811);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(126, E'SMY', 95, E'StarZone 30', 141817, NULL, NULL, NULL, '2024-06-12 12:08:27', '2024-06-12 15:18:35', 206306, 269369);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(127, E'SMY', 95, E'StarZone 50', 223049, NULL, NULL, NULL, '2024-06-12 12:08:46', '2024-06-12 15:18:42', 314414, 404505);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(128, E'SMY', 95, E'StarZone 100', 453857, NULL, NULL, NULL, '2024-06-12 12:09:07', '2024-06-12 15:18:51', 584685, 719820);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(129, E'SMY', 95, E'StarZone 150', 511424, NULL, NULL, NULL, '2024-06-12 15:19:49', '2024-06-12 15:19:49', 656757, 809910);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(130, E'SMY', 95, E'StarZone 200', 749438, NULL, NULL, NULL, '2024-06-12 15:20:16', '2024-06-12 15:20:16', 900000, 1080180);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(131, E'SMY', 95, E'StarZone 300', 916864, NULL, NULL, NULL, '2024-06-12 15:20:38', '2024-06-12 15:20:38', 1107207, 1350450);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(132, E'SMY', 96, E'StarBiz 30', 169773, NULL, NULL, NULL, '2024-06-12 15:21:24', '2024-06-12 15:21:24', 224324, 359459);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(133, E'SMY', 96, E'StarBiz 50 (best seller)', 267031, NULL, NULL, NULL, '2024-06-12 15:21:43', '2024-06-12 15:21:43', 341441, 494595);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(134, E'SMY', 96, E'StarBiz 100', 427345, NULL, NULL, NULL, '2024-06-12 15:22:04', '2024-06-12 15:22:04', 629730, 900000);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(135, E'SMY', 96, E'StarBiz 150', 597581, NULL, NULL, NULL, '2024-06-12 15:22:20', '2024-06-12 15:22:20', 900000, 1080180);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(136, E'SMY', 96, E'StarBiz 200', 753379, NULL, NULL, NULL, '2024-06-12 15:22:35', '2024-06-12 15:22:35', 1125225, 1350450);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(137, E'SMY', 96, E'StarBiz 300', 1040169, NULL, NULL, NULL, '2024-06-12 15:22:54', '2024-06-12 15:22:54', 1620721, 1981081);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(138, E'SMY', 98, E'StarLight 20', 222850, NULL, NULL, NULL, '2024-06-12 15:24:32', '2024-06-12 15:24:32', 386486, 809910);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(139, E'SMY', 98, E'StarLight 30', 441524, NULL, NULL, NULL, '2024-06-12 15:24:47', '2024-06-12 15:24:47', 494595, 990090);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(140, E'SMY', 98, E'StarLight 40', 600787, NULL, NULL, NULL, '2024-06-12 15:25:05', '2024-06-12 15:25:05', 719820, 1260360);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(141, E'SMY', 98, E'StarLight 50', 748045, NULL, NULL, NULL, '2024-06-12 15:25:19', '2024-06-12 15:25:19', 854955, 1530631);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(142, E'SMY', 98, E'StarLight 100', 1160615, NULL, NULL, NULL, '2024-06-12 15:25:37', '2024-06-12 15:25:37', 1350450, 2341441);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(144, E'WA', 92, E'MITRA300 Mbps', 7561943, NULL, NULL, NULL, '2024-06-12 15:26:29', '2024-06-12 15:26:29', 12500000, 22500000);
INSERT INTO demo_winter_erp.public.produk_layanan(id, nama_tenant, produk_id, nama, harga, keterangan, akun_hutang, akun_piutang, created_at, updated_at, harga_terendah, harga_tertinggi) VALUES
(143, E'SMY', 98, E'StarLight 300', 1508070, NULL, E'36', E'35', '2024-06-12 15:25:55', '2024-06-13 14:02:39', 2071171, 2972072);