--
-- Script was generated by Devart dbForge Studio for PostgreSQL, Version 3.1.839.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 24/07/2024 10:25:39
-- Server version: 14.10
--

INSERT INTO demo_winter_erp.public.lokasi(id, nama) VALUES
(2, E'Bogor');
INSERT INTO demo_winter_erp.public.lokasi(id, nama) VALUES
(3, E'Ciamis');
INSERT INTO demo_winter_erp.public.lokasi(id, nama) VALUES
(4, E'Garut');