--
-- Script was generated by Devart dbForge Studio for PostgreSQL, Version 3.1.839.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 24/07/2024 10:25:56
-- Server version: 14.10
--

INSERT INTO demo_winter_erp.public.role_dashboard_permissions(id, role_id, dashboard_component_code, created_at, updated_at) VALUES
(3, 77, E'sales-activity-card', '2024-06-20 09:19:19', '2024-06-20 09:19:19');
INSERT INTO demo_winter_erp.public.role_dashboard_permissions(id, role_id, dashboard_component_code, created_at, updated_at) VALUES
(4, 77, E'sales-prospek-card', '2024-06-20 09:19:19', '2024-06-20 09:19:19');
INSERT INTO demo_winter_erp.public.role_dashboard_permissions(id, role_id, dashboard_component_code, created_at, updated_at) VALUES
(5, 77, E'progress-complete-sales-activity-card', '2024-06-20 09:19:19', '2024-06-20 09:19:19');
INSERT INTO demo_winter_erp.public.role_dashboard_permissions(id, role_id, dashboard_component_code, created_at, updated_at) VALUES
(6, 77, E'installation-activation-sales-prospek-card', '2024-06-20 09:19:19', '2024-06-20 09:19:19');
INSERT INTO demo_winter_erp.public.role_dashboard_permissions(id, role_id, dashboard_component_code, created_at, updated_at) VALUES
(7, 77, E'top-ten-sales-table', '2024-06-20 09:19:19', '2024-06-20 09:19:19');
INSERT INTO demo_winter_erp.public.role_dashboard_permissions(id, role_id, dashboard_component_code, created_at, updated_at) VALUES
(8, 77, E'3-last-days-of-sales-prospek', '2024-06-20 09:19:19', '2024-06-20 09:19:19');
INSERT INTO demo_winter_erp.public.role_dashboard_permissions(id, role_id, dashboard_component_code, created_at, updated_at) VALUES
(9, 77, E'sales-activity-graphic', '2024-06-20 09:19:19', '2024-06-20 09:19:19');
INSERT INTO demo_winter_erp.public.role_dashboard_permissions(id, role_id, dashboard_component_code, created_at, updated_at) VALUES
(21, 7, E'sales-prospek-card', '2024-07-02 10:53:35', '2024-07-02 10:53:35');
INSERT INTO demo_winter_erp.public.role_dashboard_permissions(id, role_id, dashboard_component_code, created_at, updated_at) VALUES
(22, 7, E'ticket-completion-percentage-card', '2024-07-02 10:53:35', '2024-07-02 10:53:35');
INSERT INTO demo_winter_erp.public.role_dashboard_permissions(id, role_id, dashboard_component_code, created_at, updated_at) VALUES
(23, 7, E'pending-ticket-card', '2024-07-02 10:53:35', '2024-07-02 10:53:35');
INSERT INTO demo_winter_erp.public.role_dashboard_permissions(id, role_id, dashboard_component_code, created_at, updated_at) VALUES
(24, 7, E'pending-sales-prospek-percentage-card', '2024-07-02 10:53:35', '2024-07-02 10:53:35');
INSERT INTO demo_winter_erp.public.role_dashboard_permissions(id, role_id, dashboard_component_code, created_at, updated_at) VALUES
(25, 7, E'rekapitulasi-pelanggan-card', '2024-07-02 10:53:35', '2024-07-02 10:53:35');
INSERT INTO demo_winter_erp.public.role_dashboard_permissions(id, role_id, dashboard_component_code, created_at, updated_at) VALUES
(26, 7, E'pelanggan-aktivasi-card', '2024-07-02 10:53:35', '2024-07-02 10:53:35');
INSERT INTO demo_winter_erp.public.role_dashboard_permissions(id, role_id, dashboard_component_code, created_at, updated_at) VALUES
(27, 7, E'3-last-days-of-sales-prospek', '2024-07-02 10:53:35', '2024-07-02 10:53:35');
INSERT INTO demo_winter_erp.public.role_dashboard_permissions(id, role_id, dashboard_component_code, created_at, updated_at) VALUES
(28, 7, E'trouble-ticket-graphic', '2024-07-02 10:53:35', '2024-07-02 10:53:35');
INSERT INTO demo_winter_erp.public.role_dashboard_permissions(id, role_id, dashboard_component_code, created_at, updated_at) VALUES
(29, 7, E'customer-support-graphic', '2024-07-02 10:53:35', '2024-07-02 10:53:35');
INSERT INTO demo_winter_erp.public.role_dashboard_permissions(id, role_id, dashboard_component_code, created_at, updated_at) VALUES
(43, 41, E'pending-sales-prospek-card', '2024-07-18 10:41:15', '2024-07-18 10:41:15');
INSERT INTO demo_winter_erp.public.role_dashboard_permissions(id, role_id, dashboard_component_code, created_at, updated_at) VALUES
(44, 41, E'pending-schedule-sales-prospek-card', '2024-07-18 10:41:15', '2024-07-18 10:41:15');
INSERT INTO demo_winter_erp.public.role_dashboard_permissions(id, role_id, dashboard_component_code, created_at, updated_at) VALUES
(45, 41, E'sales-activity-card', '2024-07-18 10:41:15', '2024-07-18 10:41:15');
INSERT INTO demo_winter_erp.public.role_dashboard_permissions(id, role_id, dashboard_component_code, created_at, updated_at) VALUES
(46, 41, E'sales-prospek-card', '2024-07-18 10:41:15', '2024-07-18 10:41:15');
INSERT INTO demo_winter_erp.public.role_dashboard_permissions(id, role_id, dashboard_component_code, created_at, updated_at) VALUES
(47, 3, E'pending-sales-prospek-card', '2024-07-19 13:51:09', '2024-07-19 13:51:09');
INSERT INTO demo_winter_erp.public.role_dashboard_permissions(id, role_id, dashboard_component_code, created_at, updated_at) VALUES
(48, 3, E'sales-prospek-card', '2024-07-19 13:51:09', '2024-07-19 13:51:09');
INSERT INTO demo_winter_erp.public.role_dashboard_permissions(id, role_id, dashboard_component_code, created_at, updated_at) VALUES
(49, 3, E'ticket-completion-percentage-card', '2024-07-19 13:51:09', '2024-07-19 13:51:09');
INSERT INTO demo_winter_erp.public.role_dashboard_permissions(id, role_id, dashboard_component_code, created_at, updated_at) VALUES
(50, 3, E'installation-activation-sales-prospek-card', '2024-07-19 13:51:09', '2024-07-19 13:51:09');
INSERT INTO demo_winter_erp.public.role_dashboard_permissions(id, role_id, dashboard_component_code, created_at, updated_at) VALUES
(51, 3, E'pending-ticket-card', '2024-07-19 13:51:09', '2024-07-19 13:51:09');
INSERT INTO demo_winter_erp.public.role_dashboard_permissions(id, role_id, dashboard_component_code, created_at, updated_at) VALUES
(52, 3, E'soft-survey-graphic', '2024-07-19 13:51:09', '2024-07-19 13:51:09');
INSERT INTO demo_winter_erp.public.role_dashboard_permissions(id, role_id, dashboard_component_code, created_at, updated_at) VALUES
(53, 3, E'survey-onsite-graphic', '2024-07-19 13:51:09', '2024-07-19 13:51:09');
INSERT INTO demo_winter_erp.public.role_dashboard_permissions(id, role_id, dashboard_component_code, created_at, updated_at) VALUES
(54, 3, E'instalasi-graphic', '2024-07-19 13:51:09', '2024-07-19 13:51:09');
INSERT INTO demo_winter_erp.public.role_dashboard_permissions(id, role_id, dashboard_component_code, created_at, updated_at) VALUES
(55, 3, E'aktivasi-graphic', '2024-07-19 13:51:09', '2024-07-19 13:51:09');
INSERT INTO demo_winter_erp.public.role_dashboard_permissions(id, role_id, dashboard_component_code, created_at, updated_at) VALUES
(56, 3, E'trouble-ticket-graphic', '2024-07-19 13:51:09', '2024-07-19 13:51:09');
INSERT INTO demo_winter_erp.public.role_dashboard_permissions(id, role_id, dashboard_component_code, created_at, updated_at) VALUES
(57, 3, E'customer-support-graphic', '2024-07-19 13:51:09', '2024-07-19 13:51:09');
INSERT INTO demo_winter_erp.public.role_dashboard_permissions(id, role_id, dashboard_component_code, created_at, updated_at) VALUES
(58, 3, E'sales-activity-graphic', '2024-07-19 13:51:09', '2024-07-19 13:51:09');