--
-- Script was generated by Devart dbForge Studio for PostgreSQL, Version 3.1.839.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 24/07/2024 10:25:56
-- Server version: 14.10
--

INSERT INTO demo_winter_erp.public.role_permission_customs(id, permission_id, parent_slug, permission_name, is_checked, created_at, updated_at) VALUES
(4, NULL, E'bantuan-pelanggan-trouble', E'input-aktifitas', true, '2024-03-02 03:25:08', '2024-03-02 03:25:08');
INSERT INTO demo_winter_erp.public.role_permission_customs(id, permission_id, parent_slug, permission_name, is_checked, created_at, updated_at) VALUES
(5, NULL, E'bantuan-pelanggan-trouble', E'input-aktifitas2', true, '2024-03-02 05:28:17', '2024-03-02 05:28:17');