--
-- Script was generated by Devart dbForge Studio for PostgreSQL, Version 3.1.839.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 24/07/2024 10:25:32
-- Server version: 14.10
--

INSERT INTO demo_winter_erp.public.alasan_penolakan(id, alasan, created_at, updated_at) VALUES
(1, E'ga bener', '2024-01-15 12:49:51', '2024-01-15 12:49:51');
INSERT INTO demo_winter_erp.public.alasan_penolakan(id, alasan, created_at, updated_at) VALUES
(2, E'check too', '2024-01-19 07:46:18', '2024-01-19 12:35:47');
INSERT INTO demo_winter_erp.public.alasan_penolakan(id, alasan, created_at, updated_at) VALUES
(5, E'sudah berlangganan yang lain', '2024-01-23 06:40:25', '2024-01-23 06:40:25');
INSERT INTO demo_winter_erp.public.alasan_penolakan(id, alasan, created_at, updated_at) VALUES
(6, E'mahal', '2024-01-23 06:40:29', '2024-01-23 06:40:29');