--
-- Script was generated by Devart dbForge Studio for PostgreSQL, Version 3.1.839.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 24/07/2024 10:25:32
-- Server version: 14.10
--

INSERT INTO demo_winter_erp.public.aktivasi_detail(id, aktivasi_id, nama_item, jumlah, created_at, updated_at) VALUES
(65, 79, E'Item1', 5, '2024-07-22 22:00:21', '2024-07-22 22:00:21');
INSERT INTO demo_winter_erp.public.aktivasi_detail(id, aktivasi_id, nama_item, jumlah, created_at, updated_at) VALUES
(66, 80, E'Item1', 5, '2024-07-23 05:32:09', '2024-07-23 05:32:09');