--
-- Script was generated by Devart dbForge Studio for PostgreSQL, Version 3.1.839.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 24/07/2024 10:25:57
-- Server version: 14.10
--

INSERT INTO demo_winter_erp.public.roles(id, name, created_at, updated_at, mark_as_sales, mark_as_noc, mark_as_teknisi) VALUES
(7, E'Customer Service', '2024-01-05 06:48:47', '2024-01-05 06:48:47', false, false, false);
INSERT INTO demo_winter_erp.public.roles(id, name, created_at, updated_at, mark_as_sales, mark_as_noc, mark_as_teknisi) VALUES
(5, E'Admin Teknis', '2023-12-23 03:57:42', '2024-01-12 02:48:46', false, false, false);
INSERT INTO demo_winter_erp.public.roles(id, name, created_at, updated_at, mark_as_sales, mark_as_noc, mark_as_teknisi) VALUES
(41, E'Admin', NULL, NULL, false, false, false);
INSERT INTO demo_winter_erp.public.roles(id, name, created_at, updated_at, mark_as_sales, mark_as_noc, mark_as_teknisi) VALUES
(4, E'Finance', '2023-12-23 03:56:44', '2024-04-13 09:45:58', false, false, false);
INSERT INTO demo_winter_erp.public.roles(id, name, created_at, updated_at, mark_as_sales, mark_as_noc, mark_as_teknisi) VALUES
(2, E'Sales', '2023-12-23 03:54:14', '2024-05-19 17:33:46', true, false, false);
INSERT INTO demo_winter_erp.public.roles(id, name, created_at, updated_at, mark_as_sales, mark_as_noc, mark_as_teknisi) VALUES
(3, E'Teknisi', '2023-12-23 03:56:11', '2024-05-20 08:58:04', false, true, true);
INSERT INTO demo_winter_erp.public.roles(id, name, created_at, updated_at, mark_as_sales, mark_as_noc, mark_as_teknisi) VALUES
(77, E'Kadiv Komersial', '2024-06-13 14:35:31', '2024-06-13 14:35:31', false, false, false);