--
-- Script was generated by Devart dbForge Studio for PostgreSQL, Version 3.1.839.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 24/07/2024 10:25:33
-- Server version: 14.10
--

INSERT INTO demo_winter_erp.public.biaya_invoices(id, nama_biaya, nominal_biaya, pajak, penagihan_bayar, mekanisme_bayar, nomor_invoice, keterangan_biaya, created_at, updated_at) VALUES
(1, E'Bdndsak', 20000, E'"[{\\"pajak\\":\\"11.00\\",\\"value\\":\\"on\\"}]"', E'null', E'prabayar', E'INVOT24050001', E'null', '2024-05-21 11:50:01', '2024-05-21 11:50:01');
INSERT INTO demo_winter_erp.public.biaya_invoices(id, nama_biaya, nominal_biaya, pajak, penagihan_bayar, mekanisme_bayar, nomor_invoice, keterangan_biaya, created_at, updated_at) VALUES
(9, E'Bdndsak', 12312, E'"[{\\"pajak\\":\\"11.00\\",\\"value\\":\\"on\\"}]"', E'null', E'prabayar', E'INVOT24050002', E'null', '2024-05-30 07:24:37', '2024-05-30 07:24:37');
INSERT INTO demo_winter_erp.public.biaya_invoices(id, nama_biaya, nominal_biaya, pajak, penagihan_bayar, mekanisme_bayar, nomor_invoice, keterangan_biaya, created_at, updated_at) VALUES
(10, E'JKLD PERIODE APR', 40000000, E'"[{\\"pajak\\":\\"11.00\\",\\"value\\":\\"on\\"}]"', E'null', E'prabayar', E'INVOT24050006', E'null', '2024-05-30 15:16:54', '2024-05-30 15:16:54');
INSERT INTO demo_winter_erp.public.biaya_invoices(id, nama_biaya, nominal_biaya, pajak, penagihan_bayar, mekanisme_bayar, nomor_invoice, keterangan_biaya, created_at, updated_at) VALUES
(11, E'Biaya Registrasi', 2000000, E'"[{\\"pajak\\":\\"11.00\\",\\"value\\":\\"on\\"}]"', E'null', E'prabayar', E'INVOT24050007', E'null', '2024-05-30 15:17:28', '2024-05-30 15:17:28');
INSERT INTO demo_winter_erp.public.biaya_invoices(id, nama_biaya, nominal_biaya, pajak, penagihan_bayar, mekanisme_bayar, nomor_invoice, keterangan_biaya, created_at, updated_at) VALUES
(12, E'Bdndsak', 20000, E'"[{\\"pajak\\":\\"11.00\\",\\"value\\":\\"on\\"}]"', E'null', E'prabayar', E'INVOT24050008', E'null', '2024-05-30 20:30:12', '2024-05-30 20:30:12');