--
-- Script was generated by Devart dbForge Studio for PostgreSQL, Version 3.1.839.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 24/07/2024 10:25:44
-- Server version: 14.10
--

INSERT INTO demo_winter_erp.public.pajak(id, nama_tenant, nama, persentase_pajak, created_at, updated_at) VALUES
(1, E'SMY', E'PPN', 11, '2024-01-23 04:32:43', '2024-01-23 04:32:43');
INSERT INTO demo_winter_erp.public.pajak(id, nama_tenant, nama, persentase_pajak, created_at, updated_at) VALUES
(35, E'SMY', E'Pph 21', 2, '2024-02-06 04:18:29', '2024-02-06 04:18:29');
INSERT INTO demo_winter_erp.public.pajak(id, nama_tenant, nama, persentase_pajak, created_at, updated_at) VALUES
(69, E'SMY', E'Zakat Penghasilan', 3, '2024-04-13 09:53:37', '2024-04-13 09:54:29');