--
-- Script was generated by Devart dbForge Studio for PostgreSQL, Version 3.1.839.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 24/07/2024 10:25:58
-- Server version: 14.10
--

INSERT INTO demo_winter_erp.public.soft_survey_details(id, soft_survey_id, nama_item, jumlah, created_at, updated_at) VALUES
(146, 197, E'Router', 1, '2024-07-02 11:05:30', '2024-07-02 11:05:30');
INSERT INTO demo_winter_erp.public.soft_survey_details(id, soft_survey_id, nama_item, jumlah, created_at, updated_at) VALUES
(147, 197, E'Router 2', 1, '2024-07-02 11:05:30', '2024-07-02 11:05:30');
INSERT INTO demo_winter_erp.public.soft_survey_details(id, soft_survey_id, nama_item, jumlah, created_at, updated_at) VALUES
(179, 230, E'Item 1', 2, '2024-07-22 12:30:54', '2024-07-22 12:30:54');
INSERT INTO demo_winter_erp.public.soft_survey_details(id, soft_survey_id, nama_item, jumlah, created_at, updated_at) VALUES
(180, 230, E'Item 2', 2, '2024-07-22 12:30:54', '2024-07-22 12:30:54');
INSERT INTO demo_winter_erp.public.soft_survey_details(id, soft_survey_id, nama_item, jumlah, created_at, updated_at) VALUES
(181, 231, E'Item 1', 2, '2024-07-22 21:39:43', '2024-07-22 21:39:43');
INSERT INTO demo_winter_erp.public.soft_survey_details(id, soft_survey_id, nama_item, jumlah, created_at, updated_at) VALUES
(182, 232, E'Item 1', 2, '2024-07-23 05:21:19', '2024-07-23 05:21:19');
INSERT INTO demo_winter_erp.public.soft_survey_details(id, soft_survey_id, nama_item, jumlah, created_at, updated_at) VALUES
(183, 232, E'Item 2', 2, '2024-07-23 05:21:19', '2024-07-23 05:21:19');
INSERT INTO demo_winter_erp.public.soft_survey_details(id, soft_survey_id, nama_item, jumlah, created_at, updated_at) VALUES
(184, 233, E'Item 1', 2, '2024-07-23 05:55:25', '2024-07-23 05:55:25');