--
-- Script was generated by Devart dbForge Studio for PostgreSQL, Version 3.1.839.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 24/07/2024 10:25:32
-- Server version: 14.10
--

INSERT INTO demo_winter_erp.public.akun(id, nama_tenant, type, nomor_akun, nama_akun, active, created_at, updated_at) VALUES
(36, E'SMY', E'Pengeluaran', 5101001, E'BIAYA AKSES INTERNET', true, '2024-02-20 07:13:29', '2024-02-20 07:13:29');
INSERT INTO demo_winter_erp.public.akun(id, nama_tenant, type, nomor_akun, nama_akun, active, created_at, updated_at) VALUES
(37, E'SMY', E'Pengeluaran', 5101002, E'BIAYA SEWA TOWER/ POP/ RACK', true, '2024-03-05 10:40:25', '2024-03-05 11:46:13');
INSERT INTO demo_winter_erp.public.akun(id, nama_tenant, type, nomor_akun, nama_akun, active, created_at, updated_at) VALUES
(38, E'SMY', E'Pengeluaran', 5101004, E'BIAYA INSTALASI & PEMASANGAN', true, '2024-03-05 10:40:51', '2024-03-05 11:46:17');
INSERT INTO demo_winter_erp.public.akun(id, nama_tenant, type, nomor_akun, nama_akun, active, created_at, updated_at) VALUES
(39, E'SMY', E'Harga Pokok Penjualan', 5202003, E'ATK & CETAKAN', true, '2024-03-05 11:47:28', '2024-03-05 11:47:28');
INSERT INTO demo_winter_erp.public.akun(id, nama_tenant, type, nomor_akun, nama_akun, active, created_at, updated_at) VALUES
(35, E'SMY', E'Penghasilan', 4102001, E'PENDAPATAN INTERNET', true, '2024-02-20 07:13:02', '2024-04-15 12:26:38');
INSERT INTO demo_winter_erp.public.akun(id, nama_tenant, type, nomor_akun, nama_akun, active, created_at, updated_at) VALUES
(41, E'WA', E'Aktiva Terkini', 1, E'test', true, '2024-06-11 12:40:53', '2024-06-11 12:40:53');