--
-- Script was generated by Devart dbForge Studio for PostgreSQL, Version 3.1.839.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 24/07/2024 10:25:54
-- Server version: 14.10
--

INSERT INTO demo_winter_erp.public.rincian_biaya_langganans(id, langganan_id, nomor_langganan, metode_pembayaran, no_rekening, created_at, updated_at, pajak) VALUES
(518, 603, E'FB/0324/0001', NULL, NULL, '2024-03-01 21:34:22', '2024-03-01 21:34:22', '0');
INSERT INTO demo_winter_erp.public.rincian_biaya_langganans(id, langganan_id, nomor_langganan, metode_pembayaran, no_rekening, created_at, updated_at, pajak) VALUES
(519, 604, E'FB/0324/0002', NULL, NULL, '2024-03-02 04:30:42', '2024-03-02 04:30:42', '0');
INSERT INTO demo_winter_erp.public.rincian_biaya_langganans(id, langganan_id, nomor_langganan, metode_pembayaran, no_rekening, created_at, updated_at, pajak) VALUES
(520, 605, E'FB/0324/0003', NULL, NULL, '2024-03-02 05:59:16', '2024-03-02 05:59:16', '0');
INSERT INTO demo_winter_erp.public.rincian_biaya_langganans(id, langganan_id, nomor_langganan, metode_pembayaran, no_rekening, created_at, updated_at, pajak) VALUES
(521, 607, E'FB/0324/0001', NULL, NULL, '2024-03-02 14:07:34', '2024-03-02 14:07:34', '0');
INSERT INTO demo_winter_erp.public.rincian_biaya_langganans(id, langganan_id, nomor_langganan, metode_pembayaran, no_rekening, created_at, updated_at, pajak) VALUES
(522, 608, E'FB/0324/0001', NULL, NULL, '2024-03-02 14:46:13', '2024-03-02 14:46:13', '0');