--
-- Script was generated by Devart dbForge Studio for PostgreSQL, Version 3.1.839.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 24/07/2024 10:26:01
-- Server version: 14.10
--

INSERT INTO demo_winter_erp.public.survey_onsites(id, sales_prospek_id, soft_survey_id, tanggal, media_transmisi, jenis_perangkat, nama_perangkat, jarak, jenis_kabel, panjang_kabel, ada_tower, foto_file, foto_file1, foto_file2, foto_file3, hasil_survey, created_at, updated_at, uid, nama_tenant) VALUES
(207, 271, 230, '23/07/2024 12:30:00.000000+07 AD', E'wireless', E'router', E'Perangkat1', '100', E'router', '150', true, NULL, NULL, NULL, NULL, E'Selesai.', '2024-07-22 21:38:06', '2024-07-22 21:38:06', E'anggi2', E'CF');
INSERT INTO demo_winter_erp.public.survey_onsites(id, sales_prospek_id, soft_survey_id, tanggal, media_transmisi, jenis_perangkat, nama_perangkat, jarak, jenis_kabel, panjang_kabel, ada_tower, foto_file, foto_file1, foto_file2, foto_file3, hasil_survey, created_at, updated_at, uid, nama_tenant) VALUES
(208, 274, 231, '22/07/2024 21:39:00.000000+07 AD', E'wireless', E'router', E'Perangkat1', '200', E'router', '200', true, NULL, NULL, NULL, NULL, E'Ok', '2024-07-22 21:42:46', '2024-07-22 21:42:46', E'anggi2', E'CF');
INSERT INTO demo_winter_erp.public.survey_onsites(id, sales_prospek_id, soft_survey_id, tanggal, media_transmisi, jenis_perangkat, nama_perangkat, jarak, jenis_kabel, panjang_kabel, ada_tower, foto_file, foto_file1, foto_file2, foto_file3, hasil_survey, created_at, updated_at, uid, nama_tenant) VALUES
(209, 272, 232, '23/07/2024 05:20:00.000000+07 AD', E'fo', E'modem', E'Perangkat1', '150', E'modem', '200', true, NULL, NULL, NULL, NULL, E'Selesai', '2024-07-23 05:24:41', '2024-07-23 05:24:41', E'anggi2', E'CF');
INSERT INTO demo_winter_erp.public.survey_onsites(id, sales_prospek_id, soft_survey_id, tanggal, media_transmisi, jenis_perangkat, nama_perangkat, jarak, jenis_kabel, panjang_kabel, ada_tower, foto_file, foto_file1, foto_file2, foto_file3, hasil_survey, created_at, updated_at, uid, nama_tenant) VALUES
(210, 273, 233, '23/07/2024 07:54:00.000000+07 AD', E'wireless', E'router', E'Perangkat1', '150', E'modem', '150', true, NULL, NULL, NULL, NULL, E'Selesai', '2024-07-23 05:57:56', '2024-07-23 05:57:56', E'anggi2', E'CF');