--
-- Script was generated by Devart dbForge Studio for PostgreSQL, Version 3.1.839.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 24/07/2024 10:25:58
-- Server version: 14.10
--

INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(468, 270, 1, E'Badrun', E'sales_prospek', E'Sales Prospek dibuat', E'#', NULL, '2024-06-15 08:34:19', '2024-06-15 08:34:19');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(469, 271, 103, E'Desi Ria Puspita', E'sales_prospek', E'Sales Prospek dibuat', E'#', NULL, '2024-06-24 13:44:49', '2024-06-24 13:44:49');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(470, 272, 112, E'Deita Ardhetya Oemar', E'sales_prospek', E'Sales Prospek dibuat', E'#', NULL, '2024-06-24 13:54:04', '2024-06-24 13:54:04');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(471, 273, 112, E'Deita Ardhetya Oemar', E'sales_prospek', E'Sales Prospek dibuat', E'#', NULL, '2024-06-26 14:12:49', '2024-06-26 14:12:49');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(472, 274, 112, E'Deita Ardhetya Oemar', E'sales_prospek', E'Sales Prospek dibuat', E'#', NULL, '2024-06-27 13:28:32', '2024-06-27 13:28:32');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(473, 275, 1, E'Admin ERP', E'sales_prospek', E'Sales Prospek dibuat', E'#', NULL, '2024-06-29 21:37:33', '2024-06-29 21:37:33');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(474, 276, 1, E'Admin ERP', E'sales_prospek', E'Sales Prospek dibuat', E'#', NULL, '2024-07-02 08:31:50', '2024-07-02 08:31:50');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(475, 276, 90, E'Maurizka Arrifa Khalwannisa Rossano', E'request_soft_survey', E'<b>Maurizka Arrifa Khalwannisa Rossano</b> mengajukan request soft survey', E'/sales-prospek/softsurveys', NULL, '2024-07-02 11:03:16', '2024-07-02 11:03:16');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(476, 276, 89, E'Dita Nur Puspita', E'soft_survey', E'Pengisian hasil soft survey', E'/sales-prospek/softsurveys', NULL, '2024-07-02 11:05:30', '2024-07-02 11:05:30');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(477, 276, 90, E'Maurizka Arrifa Khalwannisa Rossano', E'jadwal_survey_onsite', E'Penjadwalan Survey Onsite', E'/sales-prospek/surveyonsites', NULL, '2024-07-02 11:06:44', '2024-07-02 11:06:44');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(509, 309, 1, E'Admin ERP', E'sales_prospek', E'Sales Prospek dibuat', E'#', NULL, '2024-07-08 15:58:47', '2024-07-08 15:58:47');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(510, 274, 1, E'Admin ERP', E'request_soft_survey', E'<b>Admin ERP</b> mengajukan request soft survey', E'/sales-prospek/softsurveys', NULL, '2024-07-08 21:09:18', '2024-07-08 21:09:18');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(511, 271, 90, E'Maurizka Arrifa Khalwannisa Rossano', E'request_soft_survey', E'<b>Maurizka Arrifa Khalwannisa Rossano</b> mengajukan request soft survey', E'/sales-prospek/softsurveys', NULL, '2024-07-22 12:29:05', '2024-07-22 12:29:05');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(512, 271, 15, E'Anggi Nugraha', E'soft_survey', E'Pengisian hasil soft survey', E'/sales-prospek/softsurveys', NULL, '2024-07-22 12:30:54', '2024-07-22 12:30:54');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(513, 271, 90, E'Maurizka Arrifa Khalwannisa Rossano', E'jadwal_survey_onsite', E'Penjadwalan Survey Onsite', E'/sales-prospek/surveyonsites', NULL, '2024-07-22 12:32:08', '2024-07-22 12:32:08');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(516, 271, 15, E'Anggi Nugraha', E'survey_onsite', E'Pelaksanaan Survey Onsite', E'/sales-prospek/surveyonsites', NULL, '2024-07-22 21:38:06', '2024-07-22 21:38:06');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(517, 274, 15, E'Anggi Nugraha', E'soft_survey', E'Pengisian hasil soft survey', E'/sales-prospek/softsurveys', NULL, '2024-07-22 21:39:43', '2024-07-22 21:39:43');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(518, 274, 1, E'Admin ERP', E'jadwal_survey_onsite', E'Penjadwalan Survey Onsite', E'/sales-prospek/surveyonsites', NULL, '2024-07-22 21:40:26', '2024-07-22 21:40:26');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(519, 274, 15, E'Anggi Nugraha', E'survey_onsite', E'Pelaksanaan Survey Onsite', E'/sales-prospek/surveyonsites', NULL, '2024-07-22 21:42:46', '2024-07-22 21:42:46');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(520, 274, 1, E'Admin ERP', E'jadwal_instalasi', E'Penjadwalan Instalasi dengan Client pada 2024-07-22 21:43', E'/sales-prospek/instalasi', NULL, '2024-07-22 21:44:04', '2024-07-22 21:44:04');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(521, 274, 15, E'Anggi Nugraha', E'instalasi', E'Proses Instalasi pada 2024-07-22 21:39', E'/sales-prospek/surveyonsites', NULL, '2024-07-22 21:53:03', '2024-07-22 21:53:03');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(522, 274, 1, E'Admin ERP', E'jadwal_aktivasi', E'Penjadwalan Aktivasi pada 2024-07-22 21:56', E'/sales-prospek/surveyonsites', NULL, '2024-07-22 21:56:50', '2024-07-22 21:56:50');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(523, 274, 15, E'Anggi Nugraha', E'aktivasi', E'Proses Aktivasi', E'/sales-prospek/aktivasi', NULL, '2024-07-22 22:00:17', '2024-07-22 22:00:17');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(524, 272, 90, E'Maurizka Arrifa Khalwannisa Rossano', E'request_soft_survey', E'<b>Maurizka Arrifa Khalwannisa Rossano</b> mengajukan request soft survey', E'/sales-prospek/softsurveys', NULL, '2024-07-23 05:19:43', '2024-07-23 05:19:43');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(525, 272, 15, E'Anggi Nugraha', E'soft_survey', E'Pengisian hasil soft survey', E'/sales-prospek/softsurveys', NULL, '2024-07-23 05:21:19', '2024-07-23 05:21:19');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(526, 272, 90, E'Maurizka Arrifa Khalwannisa Rossano', E'jadwal_survey_onsite', E'Penjadwalan Survey Onsite', E'/sales-prospek/surveyonsites', NULL, '2024-07-23 05:22:43', '2024-07-23 05:22:43');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(527, 272, 15, E'Anggi Nugraha', E'survey_onsite', E'Pelaksanaan Survey Onsite', E'/sales-prospek/surveyonsites', NULL, '2024-07-23 05:24:41', '2024-07-23 05:24:41');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(528, 272, 90, E'Maurizka Arrifa Khalwannisa Rossano', E'jadwal_instalasi', E'Penjadwalan Instalasi dengan Client pada 2024-07-25 09:25', E'/sales-prospek/instalasi', NULL, '2024-07-23 05:25:52', '2024-07-23 05:25:52');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(529, 272, 15, E'Anggi Nugraha', E'instalasi', E'Proses Instalasi pada 2024-07-23 05:20', E'/sales-prospek/surveyonsites', NULL, '2024-07-23 05:27:58', '2024-07-23 05:27:58');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(530, 272, 90, E'Maurizka Arrifa Khalwannisa Rossano', E'jadwal_aktivasi', E'Penjadwalan Aktivasi pada 2024-07-26 10:30', E'/sales-prospek/surveyonsites', NULL, '2024-07-23 05:30:13', '2024-07-23 05:30:13');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(531, 272, 15, E'Anggi Nugraha', E'aktivasi', E'Proses Aktivasi', E'/sales-prospek/aktivasi', NULL, '2024-07-23 05:32:08', '2024-07-23 05:32:08');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(532, 273, 90, E'Maurizka Arrifa Khalwannisa Rossano', E'request_soft_survey', E'<b>Maurizka Arrifa Khalwannisa Rossano</b> mengajukan request soft survey', E'/sales-prospek/softsurveys', NULL, '2024-07-23 05:54:18', '2024-07-23 05:54:18');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(533, 273, 15, E'Anggi Nugraha', E'soft_survey', E'Pengisian hasil soft survey', E'/sales-prospek/softsurveys', NULL, '2024-07-23 05:55:25', '2024-07-23 05:55:25');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(534, 273, 90, E'Maurizka Arrifa Khalwannisa Rossano', E'jadwal_survey_onsite', E'Penjadwalan Survey Onsite', E'/sales-prospek/surveyonsites', NULL, '2024-07-23 05:56:00', '2024-07-23 05:56:00');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(535, 273, 15, E'Anggi Nugraha', E'survey_onsite', E'Pelaksanaan Survey Onsite', E'/sales-prospek/surveyonsites', NULL, '2024-07-23 05:57:56', '2024-07-23 05:57:56');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(536, 273, 90, E'Maurizka Arrifa Khalwannisa Rossano', E'jadwal_instalasi', E'Penjadwalan Instalasi dengan Client pada 2024-07-24 09:20', E'/sales-prospek/instalasi', NULL, '2024-07-23 05:58:58', '2024-07-23 05:58:58');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(537, 273, 15, E'Anggi Nugraha', E'instalasi', E'Proses Instalasi pada 2024-07-23 07:54', E'/sales-prospek/surveyonsites', NULL, '2024-07-23 05:59:57', '2024-07-23 05:59:57');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(538, 273, 90, E'Maurizka Arrifa Khalwannisa Rossano', E'jadwal_aktivasi', E'Penjadwalan Aktivasi pada 2024-07-24 10:23', E'/sales-prospek/surveyonsites', NULL, '2024-07-23 06:00:42', '2024-07-23 06:00:42');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(539, 273, 15, E'Anggi Nugraha', E'aktivasi', E'Proses Aktivasi', E'/sales-prospek/aktivasi', NULL, '2024-07-23 06:01:36', '2024-07-23 06:01:36');
INSERT INTO demo_winter_erp.public.sales_prospek_timelines(id, sales_prospek_id, user_id, user_name, type, message, link, data, created_at, updated_at) VALUES
(540, 271, 1, E'Admin ERP', E'jadwal_instalasi', E'Penjadwalan Instalasi dengan Client pada 2024-07-23 06:27', E'/sales-prospek/instalasi', NULL, '2024-07-23 06:27:19', '2024-07-23 06:27:19');