--
-- Script was generated by Devart dbForge Studio for PostgreSQL, Version 3.1.839.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 24/07/2024 10:25:36
-- Server version: 14.10
--

INSERT INTO demo_winter_erp.public.jadwal_aktivasi(id, sales_prospek_id, instalasi_id, tanggal, lokasi_id, catatan, created_at, updated_at, uid) VALUES
(79, 274, 136, '22/07/2024 21:56:00.000000+07 AD', E'Sesuai', E'Ok', '2024-07-22 21:56:50', '2024-07-22 21:56:50', E'admin.erp');
INSERT INTO demo_winter_erp.public.jadwal_aktivasi(id, sales_prospek_id, instalasi_id, tanggal, lokasi_id, catatan, created_at, updated_at, uid) VALUES
(80, 272, 137, '26/07/2024 10:30:00.000000+07 AD', E'sesuai', E'oke', '2024-07-23 05:30:13', '2024-07-23 05:30:13', E'maurizka');
INSERT INTO demo_winter_erp.public.jadwal_aktivasi(id, sales_prospek_id, instalasi_id, tanggal, lokasi_id, catatan, created_at, updated_at, uid) VALUES
(81, 273, 138, '24/07/2024 10:23:00.000000+07 AD', E'sesuai', E'oke', '2024-07-23 06:00:42', '2024-07-23 06:00:42', E'maurizka');