--
-- Script was generated by Devart dbForge Studio for PostgreSQL, Version 3.1.839.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 24/07/2024 10:26:00
-- Server version: 14.10
--

INSERT INTO demo_winter_erp.public.survey_onsite_details(id, survey_onsite_id, nama_item, jumlah, created_at, updated_at, status_item) VALUES
(133, 207, E'1121', 5, '2024-07-22 21:38:18', '2024-07-22 21:38:18', NULL);
INSERT INTO demo_winter_erp.public.survey_onsite_details(id, survey_onsite_id, nama_item, jumlah, created_at, updated_at, status_item) VALUES
(134, 207, E'1198', 5, '2024-07-22 21:38:18', '2024-07-22 21:38:18', NULL);
INSERT INTO demo_winter_erp.public.survey_onsite_details(id, survey_onsite_id, nama_item, jumlah, created_at, updated_at, status_item) VALUES
(135, 208, E'1245', 5, '2024-07-22 21:42:53', '2024-07-22 21:42:53', E'Sendiri');
INSERT INTO demo_winter_erp.public.survey_onsite_details(id, survey_onsite_id, nama_item, jumlah, created_at, updated_at, status_item) VALUES
(136, 209, E'1163', 1, '2024-07-23 05:24:43', '2024-07-23 05:24:43', E'Sendiri');
INSERT INTO demo_winter_erp.public.survey_onsite_details(id, survey_onsite_id, nama_item, jumlah, created_at, updated_at, status_item) VALUES
(137, 209, E'1285', 5, '2024-07-23 05:24:43', '2024-07-23 05:24:43', E'Sewa');
INSERT INTO demo_winter_erp.public.survey_onsite_details(id, survey_onsite_id, nama_item, jumlah, created_at, updated_at, status_item) VALUES
(138, 210, E'1164', 1, '2024-07-23 05:57:58', '2024-07-23 05:57:58', E'Sewa');