--
-- Script was generated by Devart dbForge Studio for PostgreSQL, Version 3.1.839.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 24/07/2024 10:25:53
-- Server version: 14.10
--

INSERT INTO demo_winter_erp.public.produk(id, nama_tenant, kategori_id, kode, nama, created_at, updated_at) VALUES
(86, E'WA', 107, E'Wbz', E'Winbiz', '2024-06-11 11:54:09', '2024-06-11 12:40:11');
INSERT INTO demo_winter_erp.public.produk(id, nama_tenant, kategori_id, kode, nama, created_at, updated_at) VALUES
(87, E'WA', 108, E'WLG', E'Winlight', '2024-06-11 13:12:12', '2024-06-11 13:12:12');
INSERT INTO demo_winter_erp.public.produk(id, nama_tenant, kategori_id, kode, nama, created_at, updated_at) VALUES
(88, E'WA', 109, E'STRSm', E'STARLIFE *Simaya', '2024-06-11 13:16:54', '2024-06-11 13:16:54');
INSERT INTO demo_winter_erp.public.produk(id, nama_tenant, kategori_id, kode, nama, created_at, updated_at) VALUES
(89, E'WA', 109, E'WNLWin', E'WINLIFE*Winter', '2024-06-11 13:21:47', '2024-06-11 13:21:55');
INSERT INTO demo_winter_erp.public.produk(id, nama_tenant, kategori_id, kode, nama, created_at, updated_at) VALUES
(90, E'WA', 110, E'WNZ', E'WINZONE', '2024-06-11 13:50:52', '2024-06-11 13:50:52');
INSERT INTO demo_winter_erp.public.produk(id, nama_tenant, kategori_id, kode, nama, created_at, updated_at) VALUES
(91, E'WA', 111, E'ENTR', E'Enterprise', '2024-06-11 13:55:07', '2024-06-11 13:55:07');
INSERT INTO demo_winter_erp.public.produk(id, nama_tenant, kategori_id, kode, nama, created_at, updated_at) VALUES
(92, E'WA', 112, E'MTRWa', E'Mitravaganza', '2024-06-11 20:07:29', '2024-06-11 20:07:29');
INSERT INTO demo_winter_erp.public.produk(id, nama_tenant, kategori_id, kode, nama, created_at, updated_at) VALUES
(93, E'SMY', 113, E'VLC', E'Velocity', '2024-06-12 11:53:29', '2024-06-12 11:53:29');
INSERT INTO demo_winter_erp.public.produk(id, nama_tenant, kategori_id, kode, nama, created_at, updated_at) VALUES
(94, E'SMY', 113, E'VLCL', E'Velocity Lux', '2024-06-12 11:53:40', '2024-06-12 11:53:40');
INSERT INTO demo_winter_erp.public.produk(id, nama_tenant, kategori_id, kode, nama, created_at, updated_at) VALUES
(95, E'SMY', 114, E'SHStd', E'Soho Standard', '2024-06-12 12:08:04', '2024-06-12 12:08:04');
INSERT INTO demo_winter_erp.public.produk(id, nama_tenant, kategori_id, kode, nama, created_at, updated_at) VALUES
(96, E'SMY', 114, E'SHRg', E'Soho Reguler', '2024-06-12 15:21:03', '2024-06-12 15:21:03');
INSERT INTO demo_winter_erp.public.produk(id, nama_tenant, kategori_id, kode, nama, created_at, updated_at) VALUES
(98, E'SMY', 115, E'STRSM', E'STARLIGHT *SIMAYA', '2024-06-12 15:24:13', '2024-06-12 15:24:13');