--
-- Script was generated by Devart dbForge Studio for PostgreSQL, Version 3.1.839.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 24/07/2024 10:25:59
-- Server version: 14.10
--

INSERT INTO demo_winter_erp.public.soft_surveys(id, sales_prospek_id, tanggal, media_transmisi, jenis_perangkat, nama_perangkat, jarak, ada_tower, hasil_survey, created_at, updated_at, uid, nama_tenant) VALUES
(197, 276, '02/07/2024 11:04:00.000000+07 AD', E'wireless', E'router', E'Router ASD', '100', true, E'tercover', '2024-07-02 11:05:30', '2024-07-02 11:05:30', E'dita', E'WA');
INSERT INTO demo_winter_erp.public.soft_surveys(id, sales_prospek_id, tanggal, media_transmisi, jenis_perangkat, nama_perangkat, jarak, ada_tower, hasil_survey, created_at, updated_at, uid, nama_tenant) VALUES
(230, 271, '22/07/2024 12:30:00.000000+07 AD', E'wireless', E'router', E'Perangkat1', '100', true, E'Tercover', '2024-07-22 12:30:54', '2024-07-22 12:30:54', E'anggi2', E'CF');
INSERT INTO demo_winter_erp.public.soft_surveys(id, sales_prospek_id, tanggal, media_transmisi, jenis_perangkat, nama_perangkat, jarak, ada_tower, hasil_survey, created_at, updated_at, uid, nama_tenant) VALUES
(231, 274, '22/07/2024 21:39:00.000000+07 AD', E'wireless', E'router', E'Perangkat1', '200', true, E'Tercover', '2024-07-22 21:39:43', '2024-07-22 21:39:43', E'anggi2', E'CF');
INSERT INTO demo_winter_erp.public.soft_surveys(id, sales_prospek_id, tanggal, media_transmisi, jenis_perangkat, nama_perangkat, jarak, ada_tower, hasil_survey, created_at, updated_at, uid, nama_tenant) VALUES
(232, 272, '23/07/2024 05:20:00.000000+07 AD', E'fo', E'modem', E'Perangkat1', '150', true, E'Tercover', '2024-07-23 05:21:19', '2024-07-23 05:21:19', E'anggi2', E'CF');
INSERT INTO demo_winter_erp.public.soft_surveys(id, sales_prospek_id, tanggal, media_transmisi, jenis_perangkat, nama_perangkat, jarak, ada_tower, hasil_survey, created_at, updated_at, uid, nama_tenant) VALUES
(233, 273, '23/07/2024 07:54:00.000000+07 AD', E'wireless', E'router', E'Perangkat1', '150', true, E'Tercover', '2024-07-23 05:55:25', '2024-07-23 05:55:25', E'anggi2', E'CF');