--
-- Script was generated by Devart dbForge Studio for PostgreSQL, Version 3.1.839.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 24/07/2024 10:25:33
-- Server version: 14.10
--

INSERT INTO demo_winter_erp.public.biaya(id, nama, created_at, updated_at, nama_tenant, akun_hutang, akun_piutang) VALUES
(74, E'Ip Public', '2024-03-05 14:14:20', '2024-03-05 14:14:20', E'SMY', 35, 36);
INSERT INTO demo_winter_erp.public.biaya(id, nama, created_at, updated_at, nama_tenant, akun_hutang, akun_piutang) VALUES
(76, E'Beli Perangkat', '2024-03-05 14:23:30', '2024-03-20 11:55:28', E'SMY', 38, 36);
INSERT INTO demo_winter_erp.public.biaya(id, nama, created_at, updated_at, nama_tenant, akun_hutang, akun_piutang) VALUES
(75, E'Sewa Perangkat', '2024-03-05 14:18:03', '2024-03-20 11:55:33', E'SMY', 38, 36);