--
-- Script was generated by Devart dbForge Studio for PostgreSQL, Version 3.1.839.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 24/07/2024 10:25:54
-- Server version: 14.10
--

INSERT INTO demo_winter_erp.public.produk_kategori(id, nama, created_at, updated_at, nama_tenant) VALUES
(107, E'SOHO (Premium)', '2024-06-11 11:00:24', '2024-06-11 11:00:24', E'WA');
INSERT INTO demo_winter_erp.public.produk_kategori(id, nama, created_at, updated_at, nama_tenant) VALUES
(108, E'WINLIGHT', '2024-06-11 12:41:44', '2024-06-11 12:41:44', E'WA');
INSERT INTO demo_winter_erp.public.produk_kategori(id, nama, created_at, updated_at, nama_tenant) VALUES
(109, E'CYBER (Resto & Café)', '2024-06-11 13:16:29', '2024-06-11 13:16:29', E'WA');
INSERT INTO demo_winter_erp.public.produk_kategori(id, nama, created_at, updated_at, nama_tenant) VALUES
(110, E'EDUCATION ZONE', '2024-06-11 13:50:31', '2024-06-11 13:50:31', E'WA');
INSERT INTO demo_winter_erp.public.produk_kategori(id, nama, created_at, updated_at, nama_tenant) VALUES
(111, E'ENTERPRISE *WINTER ACCESS', '2024-06-11 13:54:31', '2024-06-11 13:54:31', E'WA');
INSERT INTO demo_winter_erp.public.produk_kategori(id, nama, created_at, updated_at, nama_tenant) VALUES
(112, E'MITRAVAGANZA *WINTER ACCESS', '2024-06-11 14:01:38', '2024-06-11 14:01:38', E'WA');
INSERT INTO demo_winter_erp.public.produk_kategori(id, nama, created_at, updated_at, nama_tenant) VALUES
(113, E'RESIDENTIAL', '2024-06-12 11:53:13', '2024-06-12 11:53:13', E'SMY');
INSERT INTO demo_winter_erp.public.produk_kategori(id, nama, created_at, updated_at, nama_tenant) VALUES
(114, E'BUSINESS/STARBIZ - SOHO - SIMAYA', '2024-06-12 12:07:33', '2024-06-12 12:07:33', E'SMY');
INSERT INTO demo_winter_erp.public.produk_kategori(id, nama, created_at, updated_at, nama_tenant) VALUES
(115, E'HIS (Hotel Internet Services)', '2024-06-12 15:23:59', '2024-06-12 15:23:59', E'SMY');