--
-- Script was generated by Devart dbForge Studio for PostgreSQL, Version 3.1.839.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 24/07/2024 10:25:56
-- Server version: 14.10
--

INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5435, 1603, 1, E'?tab=kategori-produk', '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5436, 1603, 2, E'?tab=kategori-produk', '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5437, 1603, 3, E'?tab=kategori-produk', '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4881, 1487, 1, E'?tab=tiket', '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4882, 1487, 1, E'?tab=tiket-terkirim', '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4883, 1488, 1, E'?tab=tiket', '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4884, 1488, 2, E'?tab=tiket', '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4885, 1488, 3, E'?tab=tiket', '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4886, 1488, 4, E'?tab=tiket', '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4887, 1488, 5, E'?tab=tiket', '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4888, 1488, 1, E'?tab=tiket-cs', '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4889, 1488, 2, E'?tab=tiket-cs', '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4890, 1488, 3, E'?tab=tiket-cs', '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4891, 1488, 4, E'?tab=tiket-cs', '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4892, 1488, 5, E'?tab=tiket-cs', '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4893, 1489, 1, E'?tab=soft-survey', '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4894, 1489, 3, E'?tab=soft-survey', '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4895, 1489, 4, E'?tab=soft-survey', '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5438, 1603, 4, E'?tab=kategori-produk', '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5439, 1603, 1, E'?tab=produk', '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5440, 1603, 2, E'?tab=produk', '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5841, 1685, 1, E'?tab=tiket', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5842, 1685, 1, E'?tab=tiket-terkirim', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5843, 1686, 1, E'?tab=tiket', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5844, 1686, 2, E'?tab=tiket', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5845, 1686, 3, E'?tab=tiket', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5846, 1686, 4, E'?tab=tiket', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5847, 1686, 5, E'?tab=tiket', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5848, 1686, 1, E'?tab=tiket-cs', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5849, 1686, 2, E'?tab=tiket-cs', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5850, 1686, 3, E'?tab=tiket-cs', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5851, 1686, 4, E'?tab=tiket-cs', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5852, 1686, 5, E'?tab=tiket-cs', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5853, 1687, 1, E'?tab=soft-survey', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5854, 1687, 3, E'?tab=soft-survey', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5855, 1687, 4, E'?tab=soft-survey', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5856, 1687, 1, E'?tab=jadwal-survey-onsite', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5441, 1603, 3, E'?tab=produk', '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5442, 1603, 4, E'?tab=produk', '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5443, 1603, 1, E'?tab=layanan', '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5444, 1603, 2, E'?tab=layanan', '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5445, 1603, 3, E'?tab=layanan', '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5446, 1603, 4, E'?tab=layanan', '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5447, 1604, 1, NULL, '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5448, 1604, 2, NULL, '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5449, 1604, 3, NULL, '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4896, 1489, 1, E'?tab=jadwal-survey-onsite', '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4897, 1489, 13, E'?tab=jadwal-survey-onsite', '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4898, 1490, 1, E'?tab=survey-onsite', '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4899, 1490, 3, E'?tab=survey-onsite', '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4900, 1490, 4, E'?tab=survey-onsite', '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4901, 1490, 1, E'?tab=jadwal-instalasi', '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4902, 1490, 10, E'?tab=jadwal-instalasi', '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4903, 1491, 1, E'?tab=instalasi', '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4904, 1491, 3, E'?tab=instalasi', '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4905, 1491, 4, E'?tab=instalasi', '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4906, 1491, 1, E'?tab=jadwal-aktivasi', '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4907, 1491, 12, E'?tab=jadwal-aktivasi', '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4908, 1492, 1, NULL, '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4909, 1492, 3, NULL, '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4910, 1492, 4, NULL, '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4911, 1493, 1, NULL, '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4912, 1493, 7, NULL, '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4913, 1494, 1, NULL, '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4914, 1495, 1, NULL, '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4915, 1495, 2, NULL, '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4916, 1495, 3, NULL, '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4917, 1495, 4, NULL, '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4918, 1496, 1, E'?tab=kategori-produk', '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4919, 1496, 1, E'?tab=bandwidth', '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4920, 1496, 1, E'?tab=subjek-penawaran', '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4921, 1496, 1, E'?tab=jenis-tiket', '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4922, 1496, 2, E'?tab=jenis-tiket', '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4923, 1496, 3, E'?tab=jenis-tiket', '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4924, 1496, 4, E'?tab=jenis-tiket', '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4925, 1496, 1, E'?tab=kategori-tiket', '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4926, 1496, 1, E'?tab=lokasi', '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(4927, 1496, 1, E'?tab=list-perusahaan', '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5450, 1604, 4, NULL, '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5451, 1607, 1, E'?tab=soft-survey', '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5452, 1607, 1, E'?tab=jadwal-survey-onsite', '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5453, 1608, 1, E'?tab=survey-onsite', '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5454, 1608, 1, E'?tab=jadwal-instalasi', '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5455, 1609, 1, E'?tab=instalasi', '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5456, 1609, 1, E'?tab=jadwal-aktivasi', '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5457, 1610, 1, NULL, '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5458, 1611, 1, NULL, '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5459, 1611, 2, NULL, '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5460, 1611, 3, NULL, '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5461, 1611, 4, NULL, '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5462, 1612, 1, NULL, '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5463, 1612, 2, NULL, '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5464, 1612, 3, NULL, '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5465, 1612, 4, NULL, '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5466, 1613, 1, NULL, '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5467, 1614, 1, NULL, '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5468, 1614, 2, NULL, '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5469, 1614, 3, NULL, '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5470, 1614, 4, NULL, '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5471, 1615, 1, E'?tab=kategori-produk', '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5472, 1615, 2, E'?tab=kategori-produk', '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5473, 1615, 3, E'?tab=kategori-produk', '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5474, 1615, 4, E'?tab=kategori-produk', '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5475, 1615, 1, E'?tab=bandwidth', '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5476, 1615, 2, E'?tab=bandwidth', '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5477, 1615, 3, E'?tab=bandwidth', '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5478, 1615, 4, E'?tab=bandwidth', '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5479, 1615, 1, E'?tab=biaya', '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5480, 1615, 1, E'?tab=pajak', '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5481, 1615, 1, E'?tab=subjek-penawaran', '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5482, 1615, 2, E'?tab=subjek-penawaran', '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5483, 1615, 3, E'?tab=subjek-penawaran', '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5484, 1615, 4, E'?tab=subjek-penawaran', '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5485, 1615, 1, E'?tab=alasan-penolakan', '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5486, 1615, 2, E'?tab=alasan-penolakan', '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5487, 1615, 3, E'?tab=alasan-penolakan', '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5488, 1615, 4, E'?tab=alasan-penolakan', '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5489, 1615, 1, E'?tab=lokasi', '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5490, 1615, 1, E'?tab=list-rekening', '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5491, 1616, 1, NULL, '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5857, 1687, 13, E'?tab=jadwal-survey-onsite', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5858, 1688, 1, E'?tab=survey-onsite', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5859, 1688, 3, E'?tab=survey-onsite', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5860, 1688, 4, E'?tab=survey-onsite', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5861, 1688, 1, E'?tab=jadwal-instalasi', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5862, 1688, 10, E'?tab=jadwal-instalasi', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5863, 1689, 1, E'?tab=instalasi', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5864, 1689, 3, E'?tab=instalasi', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5865, 1689, 4, E'?tab=instalasi', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5866, 1689, 1, E'?tab=jadwal-aktivasi', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5867, 1689, 12, E'?tab=jadwal-aktivasi', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5868, 1690, 1, NULL, '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5869, 1690, 3, NULL, '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5870, 1690, 4, NULL, '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5871, 1691, 1, NULL, '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5872, 1691, 7, NULL, '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5873, 1692, 1, NULL, '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5874, 1693, 1, NULL, '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5875, 1693, 2, NULL, '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5876, 1693, 3, NULL, '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5492, 1617, 1, E'?tab=kategori-produk', '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5493, 1617, 2, E'?tab=kategori-produk', '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5494, 1617, 3, E'?tab=kategori-produk', '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5495, 1617, 4, E'?tab=kategori-produk', '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5496, 1617, 1, E'?tab=produk', '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5497, 1617, 2, E'?tab=produk', '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5498, 1617, 3, E'?tab=produk', '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5499, 1617, 4, E'?tab=produk', '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5500, 1617, 1, E'?tab=layanan', '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5501, 1617, 2, E'?tab=layanan', '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5502, 1617, 3, E'?tab=layanan', '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5503, 1617, 4, E'?tab=layanan', '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5504, 1621, 1, E'?tab=survey-onsite', '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5505, 1621, 1, E'?tab=jadwal-instalasi', '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5506, 1622, 1, E'?tab=instalasi', '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5507, 1622, 1, E'?tab=jadwal-aktivasi', '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5508, 1623, 1, NULL, '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5877, 1693, 4, NULL, '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5878, 1694, 1, NULL, '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5879, 1695, 1, NULL, '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5880, 1696, 1, E'?tab=kategori-produk', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5881, 1696, 1, E'?tab=bandwidth', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5882, 1696, 1, E'?tab=biaya', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5883, 1696, 1, E'?tab=pajak', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5884, 1696, 1, E'?tab=subjek-penawaran', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5885, 1696, 1, E'?tab=alasan-penolakan', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5886, 1696, 1, E'?tab=jenis-tiket', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5887, 1696, 2, E'?tab=jenis-tiket', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5509, 1624, 1, NULL, '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5510, 1625, 1, NULL, '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5511, 1626, 1, NULL, '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5512, 1627, 1, NULL, '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5513, 1627, 2, NULL, '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5514, 1627, 3, NULL, '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5515, 1627, 4, NULL, '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5516, 1628, 1, NULL, '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5517, 1628, 2, NULL, '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5518, 1628, 3, NULL, '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5519, 1628, 4, NULL, '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5520, 1629, 1, E'?tab=kategori-produk', '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5521, 1629, 1, E'?tab=bandwidth', '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5522, 1629, 1, E'?tab=biaya', '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5523, 1629, 2, E'?tab=biaya', '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5524, 1629, 3, E'?tab=biaya', '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5525, 1629, 4, E'?tab=biaya', '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5888, 1696, 3, E'?tab=jenis-tiket', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5889, 1696, 4, E'?tab=jenis-tiket', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5890, 1696, 1, E'?tab=kategori-tiket', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5891, 1696, 1, E'?tab=lokasi', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5892, 1696, 1, E'?tab=list-rekening', '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5526, 1629, 1, E'?tab=pajak', '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5527, 1629, 2, E'?tab=pajak', '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5528, 1629, 3, E'?tab=pajak', '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5529, 1629, 4, E'?tab=pajak', '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5530, 1629, 1, E'?tab=subjek-penawaran', '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5531, 1629, 1, E'?tab=lokasi', '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5532, 1629, 1, E'?tab=list-rekening', '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5230, 1560, 1, E'?tab=kategori-produk', '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5231, 1560, 1, E'?tab=produk', '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5232, 1560, 1, E'?tab=layanan', '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5233, 1561, 1, E'?tab=tiket', '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5234, 1561, 2, E'?tab=tiket', '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5235, 1561, 3, E'?tab=tiket', '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5236, 1561, 4, E'?tab=tiket', '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5237, 1561, 1, E'?tab=tiket-terkirim', '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5238, 1563, 1, E'?tab=soft-survey', '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5239, 1563, 8, E'?tab=soft-survey', '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5240, 1563, 1, E'?tab=jadwal-survey-onsite', '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5241, 1563, 3, E'?tab=jadwal-survey-onsite', '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5242, 1564, 1, E'?tab=survey-onsite', '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5243, 1564, 9, E'?tab=survey-onsite', '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5244, 1564, 1, E'?tab=jadwal-instalasi', '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5245, 1564, 3, E'?tab=jadwal-instalasi', '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5246, 1565, 1, E'?tab=instalasi', '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5247, 1565, 11, E'?tab=instalasi', '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5248, 1565, 1, E'?tab=jadwal-aktivasi', '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5249, 1565, 3, E'?tab=jadwal-aktivasi', '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5250, 1566, 1, NULL, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5251, 1567, 1, NULL, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5252, 1567, 6, NULL, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5253, 1568, 1, NULL, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5254, 1569, 1, NULL, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5255, 1569, 2, NULL, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5256, 1569, 3, NULL, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5257, 1569, 4, NULL, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5258, 1570, 1, NULL, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5259, 1570, 2, NULL, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5260, 1570, 3, NULL, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5261, 1570, 4, NULL, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5262, 1571, 1, NULL, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5263, 1572, 1, NULL, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5264, 1573, 1, E'?tab=kategori-produk', '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5265, 1573, 1, E'?tab=bandwidth', '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5266, 1573, 1, E'?tab=biaya', '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5267, 1573, 1, E'?tab=pajak', '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5268, 1573, 1, E'?tab=subjek-penawaran', '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5269, 1573, 1, E'?tab=alasan-penolakan', '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5270, 1573, 1, E'?tab=jenis-tiket', '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5271, 1573, 1, E'?tab=kategori-tiket', '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5272, 1573, 2, E'?tab=kategori-tiket', '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5273, 1573, 3, E'?tab=kategori-tiket', '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5274, 1573, 4, E'?tab=kategori-tiket', '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5275, 1573, 1, E'?tab=lokasi', '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5276, 1573, 1, E'?tab=list-rekening', '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5277, 1574, 1, NULL, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5278, 1574, 2, NULL, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5279, 1574, 3, NULL, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5280, 1574, 4, NULL, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5281, 1575, 1, NULL, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5282, 1575, 2, NULL, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5283, 1575, 3, NULL, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5284, 1575, 4, NULL, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5285, 1576, 1, NULL, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5533, 1630, 1, NULL, '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5534, 1630, 2, NULL, '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5535, 1630, 3, NULL, '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5536, 1630, 4, NULL, '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5537, 1631, 1, NULL, '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5538, 1631, 2, NULL, '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5539, 1631, 3, NULL, '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5897, 1705, 1, E'?tab=kategori-produk', '2024-06-20 09:17:36', '2024-06-20 09:17:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5898, 1705, 1, E'?tab=produk', '2024-06-20 09:17:36', '2024-06-20 09:17:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5899, 1705, 1, E'?tab=layanan', '2024-06-20 09:17:36', '2024-06-20 09:17:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5900, 1706, 1, NULL, '2024-06-20 09:17:36', '2024-06-20 09:17:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5901, 1712, 1, NULL, '2024-06-20 09:17:36', '2024-06-20 09:17:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5902, 1713, 1, NULL, '2024-06-20 09:17:36', '2024-06-20 09:17:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5903, 1713, 2, NULL, '2024-06-20 09:17:36', '2024-06-20 09:17:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5904, 1713, 3, NULL, '2024-06-20 09:17:36', '2024-06-20 09:17:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5905, 1713, 4, NULL, '2024-06-20 09:17:36', '2024-06-20 09:17:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5930, 1738, 1, E'?tab=kategori-produk', '2024-07-18 10:54:35', '2024-07-18 10:54:35');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5931, 1738, 2, E'?tab=kategori-produk', '2024-07-18 10:54:35', '2024-07-18 10:54:35');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5932, 1738, 3, E'?tab=kategori-produk', '2024-07-18 10:54:35', '2024-07-18 10:54:35');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5933, 1738, 4, E'?tab=kategori-produk', '2024-07-18 10:54:35', '2024-07-18 10:54:35');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5934, 1738, 1, E'?tab=produk', '2024-07-18 10:54:35', '2024-07-18 10:54:35');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5935, 1738, 2, E'?tab=produk', '2024-07-18 10:54:35', '2024-07-18 10:54:35');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5936, 1738, 3, E'?tab=produk', '2024-07-18 10:54:35', '2024-07-18 10:54:35');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5937, 1738, 4, E'?tab=produk', '2024-07-18 10:54:35', '2024-07-18 10:54:35');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5938, 1738, 1, E'?tab=layanan', '2024-07-18 10:54:35', '2024-07-18 10:54:35');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5939, 1738, 2, E'?tab=layanan', '2024-07-18 10:54:35', '2024-07-18 10:54:35');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5940, 1738, 3, E'?tab=layanan', '2024-07-18 10:54:35', '2024-07-18 10:54:35');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5941, 1738, 4, E'?tab=layanan', '2024-07-18 10:54:35', '2024-07-18 10:54:35');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5942, 1739, 1, NULL, '2024-07-18 10:54:35', '2024-07-18 10:54:35');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5943, 1739, 2, NULL, '2024-07-18 10:54:35', '2024-07-18 10:54:35');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5944, 1739, 3, NULL, '2024-07-18 10:54:35', '2024-07-18 10:54:35');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5945, 1739, 4, NULL, '2024-07-18 10:54:35', '2024-07-18 10:54:35');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5946, 1740, 1, E'?tab=tiket', '2024-07-18 10:54:35', '2024-07-18 10:54:35');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5947, 1740, 2, E'?tab=tiket', '2024-07-18 10:54:35', '2024-07-18 10:54:35');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5948, 1740, 3, E'?tab=tiket', '2024-07-18 10:54:35', '2024-07-18 10:54:35');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5949, 1740, 4, E'?tab=tiket', '2024-07-18 10:54:35', '2024-07-18 10:54:35');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5950, 1740, 1, E'?tab=tiket-terkirim', '2024-07-18 10:54:35', '2024-07-18 10:54:35');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5951, 1740, 2, E'?tab=tiket-terkirim', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5952, 1740, 3, E'?tab=tiket-terkirim', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5953, 1740, 4, E'?tab=tiket-terkirim', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5954, 1741, 1, E'?tab=tiket', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5955, 1741, 2, E'?tab=tiket', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5956, 1741, 3, E'?tab=tiket', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5957, 1741, 4, E'?tab=tiket', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5958, 1741, 5, E'?tab=tiket', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5959, 1741, 1, E'?tab=tiket-cs', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5960, 1741, 2, E'?tab=tiket-cs', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5961, 1741, 3, E'?tab=tiket-cs', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5962, 1741, 4, E'?tab=tiket-cs', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5963, 1741, 5, E'?tab=tiket-cs', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5964, 1742, 1, E'?tab=soft-survey', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5965, 1742, 3, E'?tab=soft-survey', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5966, 1742, 4, E'?tab=soft-survey', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5967, 1742, 8, E'?tab=soft-survey', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5968, 1742, 1, E'?tab=jadwal-survey-onsite', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5969, 1742, 3, E'?tab=jadwal-survey-onsite', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5970, 1742, 4, E'?tab=jadwal-survey-onsite', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5971, 1742, 13, E'?tab=jadwal-survey-onsite', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5972, 1743, 1, E'?tab=survey-onsite', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5973, 1743, 3, E'?tab=survey-onsite', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5974, 1743, 4, E'?tab=survey-onsite', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5975, 1743, 9, E'?tab=survey-onsite', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5976, 1743, 1, E'?tab=jadwal-instalasi', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5977, 1743, 3, E'?tab=jadwal-instalasi', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5978, 1743, 4, E'?tab=jadwal-instalasi', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5979, 1743, 10, E'?tab=jadwal-instalasi', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5980, 1744, 1, E'?tab=instalasi', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5981, 1744, 3, E'?tab=instalasi', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5982, 1744, 4, E'?tab=instalasi', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5983, 1744, 11, E'?tab=instalasi', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5984, 1744, 1, E'?tab=jadwal-aktivasi', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5985, 1744, 3, E'?tab=jadwal-aktivasi', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5986, 1744, 4, E'?tab=jadwal-aktivasi', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5987, 1744, 12, E'?tab=jadwal-aktivasi', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5988, 1745, 1, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5989, 1745, 3, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5990, 1745, 4, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5991, 1746, 1, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5992, 1746, 2, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5993, 1746, 3, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5994, 1746, 4, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5995, 1746, 6, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5996, 1746, 7, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5997, 1747, 1, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5998, 1747, 2, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(5999, 1747, 3, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6000, 1747, 4, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6001, 1748, 1, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6002, 1748, 2, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6003, 1748, 3, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6004, 1748, 4, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6005, 1749, 1, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6006, 1749, 3, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6007, 1750, 1, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6008, 1750, 2, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6009, 1750, 3, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6010, 1750, 4, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6011, 1751, 1, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6012, 1752, 1, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6013, 1752, 2, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6014, 1752, 3, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6015, 1752, 4, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6016, 1753, 1, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6017, 1754, 1, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6018, 1755, 1, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6019, 1756, 1, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6020, 1757, 1, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6021, 1757, 2, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6022, 1757, 3, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6023, 1757, 4, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6024, 1758, 1, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6025, 1758, 2, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6026, 1758, 3, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6027, 1758, 4, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6028, 1759, 1, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6029, 1759, 2, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6030, 1759, 3, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6031, 1759, 4, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6032, 1760, 1, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6033, 1761, 1, E'?tab=kategori-produk', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6034, 1761, 2, E'?tab=kategori-produk', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6035, 1761, 3, E'?tab=kategori-produk', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6036, 1761, 4, E'?tab=kategori-produk', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6037, 1761, 1, E'?tab=bandwidth', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6038, 1761, 2, E'?tab=bandwidth', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6039, 1761, 3, E'?tab=bandwidth', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6040, 1761, 4, E'?tab=bandwidth', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6041, 1761, 1, E'?tab=biaya', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6042, 1761, 2, E'?tab=biaya', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6043, 1761, 3, E'?tab=biaya', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6044, 1761, 4, E'?tab=biaya', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6045, 1761, 1, E'?tab=pajak', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6046, 1761, 2, E'?tab=pajak', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6047, 1761, 3, E'?tab=pajak', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6048, 1761, 4, E'?tab=pajak', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6049, 1761, 1, E'?tab=subjek-penawaran', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6050, 1761, 2, E'?tab=subjek-penawaran', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6051, 1761, 3, E'?tab=subjek-penawaran', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6052, 1761, 1, E'?tab=alasan-penolakan', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6053, 1761, 2, E'?tab=alasan-penolakan', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6054, 1761, 3, E'?tab=alasan-penolakan', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6055, 1761, 4, E'?tab=alasan-penolakan', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6056, 1761, 1, E'?tab=jenis-tiket', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6057, 1761, 2, E'?tab=jenis-tiket', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6058, 1761, 3, E'?tab=jenis-tiket', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6059, 1761, 4, E'?tab=jenis-tiket', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6060, 1761, 1, E'?tab=kategori-tiket', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6061, 1761, 2, E'?tab=kategori-tiket', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6062, 1761, 3, E'?tab=kategori-tiket', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6063, 1761, 4, E'?tab=kategori-tiket', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6064, 1761, 1, E'?tab=lokasi', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6065, 1761, 1, E'?tab=list-rekening', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6066, 1761, 1, E'?tab=list-perusahaan', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6067, 1761, 1, E'?tab=perangkat', '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6068, 1762, 1, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6069, 1762, 2, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6070, 1762, 3, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6071, 1762, 4, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6072, 1763, 1, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6073, 1763, 2, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6074, 1763, 3, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6075, 1763, 4, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6076, 1764, 1, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6077, 1764, 2, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6078, 1764, 3, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6079, 1764, 4, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6080, 1765, 1, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6081, 1765, 2, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permission_details(id, role_permission_id, permission_id, query_slug_menu, created_at, updated_at) VALUES
(6082, 1765, 3, NULL, '2024-07-18 10:54:36', '2024-07-18 10:54:36');