--
-- Script was generated by Devart dbForge Studio for PostgreSQL, Version 3.1.839.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 24/07/2024 10:25:37
-- Server version: 14.10
--

INSERT INTO demo_winter_erp.public.jadwal_surveyonsite(id, sales_prospek_id, soft_survey_id, tanggal, lokasi_id, catatan, created_at, updated_at, uid) VALUES
(146, 276, 197, '03/07/2024 11:06:00.000000+07 AD', E'sesuai titik', E'laksanakan', '2024-07-02 11:06:44', '2024-07-02 11:06:44', E'maurizka');
INSERT INTO demo_winter_erp.public.jadwal_surveyonsite(id, sales_prospek_id, soft_survey_id, tanggal, lokasi_id, catatan, created_at, updated_at, uid) VALUES
(179, 271, 230, '23/07/2024 12:30:00.000000+07 AD', E'sesuai titik', E'laksanakan', '2024-07-22 12:32:08', '2024-07-22 12:32:08', E'maurizka');
INSERT INTO demo_winter_erp.public.jadwal_surveyonsite(id, sales_prospek_id, soft_survey_id, tanggal, lokasi_id, catatan, created_at, updated_at, uid) VALUES
(180, 274, 231, '22/07/2024 21:40:00.000000+07 AD', E'Sesuai', E'Ok', '2024-07-22 21:40:26', '2024-07-22 21:40:26', E'admin.erp');
INSERT INTO demo_winter_erp.public.jadwal_surveyonsite(id, sales_prospek_id, soft_survey_id, tanggal, lokasi_id, catatan, created_at, updated_at, uid) VALUES
(181, 272, 232, '24/07/2024 10:22:00.000000+07 AD', E'Mars Selatan', E'oke', '2024-07-23 05:22:43', '2024-07-23 05:22:43', E'maurizka');
INSERT INTO demo_winter_erp.public.jadwal_surveyonsite(id, sales_prospek_id, soft_survey_id, tanggal, lokasi_id, catatan, created_at, updated_at, uid) VALUES
(182, 273, 233, '24/07/2024 09:55:00.000000+07 AD', E'sesuai', E'ok', '2024-07-23 05:56:00', '2024-07-23 05:56:00', E'maurizka');