--
-- Script was generated by Devart dbForge Studio for PostgreSQL, Version 3.1.839.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 24/07/2024 10:25:51
-- Server version: 14.10
--

INSERT INTO demo_winter_erp.public.permissions(id, name, description, created_at, updated_at) VALUES
(1, E'read', E'read data', NULL, NULL);
INSERT INTO demo_winter_erp.public.permissions(id, name, description, created_at, updated_at) VALUES
(2, E'create', E'create data', NULL, NULL);
INSERT INTO demo_winter_erp.public.permissions(id, name, description, created_at, updated_at) VALUES
(3, E'update', E'update data', NULL, NULL);
INSERT INTO demo_winter_erp.public.permissions(id, name, description, created_at, updated_at) VALUES
(4, E'delete', E'delete data', NULL, NULL);
INSERT INTO demo_winter_erp.public.permissions(id, name, description, created_at, updated_at) VALUES
(5, E'input-aktifitas', E'input aktifitas', NULL, NULL);
INSERT INTO demo_winter_erp.public.permissions(id, name, description, created_at, updated_at) VALUES
(6, E'request-survey', E'request survey', NULL, NULL);
INSERT INTO demo_winter_erp.public.permissions(id, name, description, created_at, updated_at) VALUES
(7, E'input-soft-survey', E'input soft survey', NULL, NULL);
INSERT INTO demo_winter_erp.public.permissions(id, name, description, created_at, updated_at) VALUES
(8, E'jadwal-survey-onsite', E'jadwal survey onsite', NULL, NULL);
INSERT INTO demo_winter_erp.public.permissions(id, name, description, created_at, updated_at) VALUES
(9, E'jadwal-instalasi', E'jadwal instalasi', NULL, NULL);
INSERT INTO demo_winter_erp.public.permissions(id, name, description, created_at, updated_at) VALUES
(10, E'input-instalasi', E'input instalasi', NULL, NULL);
INSERT INTO demo_winter_erp.public.permissions(id, name, description, created_at, updated_at) VALUES
(11, E'jadwal-aktivasi', E'jadwal aktivasi', NULL, NULL);
INSERT INTO demo_winter_erp.public.permissions(id, name, description, created_at, updated_at) VALUES
(12, E'input-aktivasi', E'input-aktivasi', NULL, NULL);
INSERT INTO demo_winter_erp.public.permissions(id, name, description, created_at, updated_at) VALUES
(13, E'input-survey-onsite', E'input survey onsite', NULL, NULL);