--
-- Script was generated by Devart dbForge Studio for PostgreSQL, Version 3.1.839.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 24/07/2024 10:25:58
-- Server version: 14.10
--

INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(3, 1, '2024-03-06 13:07:07', '2024-03-06 13:07:07', 1);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(3, 2, '2024-03-06 13:07:08', '2024-03-06 13:07:08', 2);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(3, 3, '2024-03-06 13:07:09', '2024-03-06 13:07:09', 3);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(3, 4, '2024-03-06 13:07:09', '2024-03-06 13:07:09', 4);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(4, 1, '2024-03-06 13:07:11', '2024-03-06 13:07:11', 5);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(4, 2, '2024-03-06 13:07:12', '2024-03-06 13:07:12', 6);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(4, 3, '2024-03-06 13:07:12', '2024-03-06 13:07:12', 7);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(4, 4, '2024-03-06 13:07:13', '2024-03-06 13:07:13', 8);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(5, 1, '2024-03-06 13:07:15', '2024-03-06 13:07:15', 9);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(5, 2, '2024-03-06 13:07:15', '2024-03-06 13:07:15', 10);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(5, 3, '2024-03-06 13:07:16', '2024-03-06 13:07:16', 11);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(5, 4, '2024-03-06 13:07:17', '2024-03-06 13:07:17', 12);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(6, 1, '2024-03-06 13:07:18', '2024-03-06 13:07:18', 13);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(6, 2, '2024-03-06 13:07:19', '2024-03-06 13:07:19', 14);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(6, 3, '2024-03-06 13:07:20', '2024-03-06 13:07:20', 15);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(6, 4, '2024-03-06 13:07:21', '2024-03-06 13:07:21', 16);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(8, 1, '2024-03-06 13:07:23', '2024-03-06 13:07:23', 17);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(8, 2, '2024-03-06 13:07:23', '2024-03-06 13:07:23', 18);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(8, 3, '2024-03-06 13:07:24', '2024-03-06 13:07:24', 19);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(8, 4, '2024-03-06 13:07:25', '2024-03-06 13:07:25', 20);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(9, 1, '2024-03-06 13:07:26', '2024-03-06 13:07:26', 21);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(9, 2, '2024-03-06 13:07:27', '2024-03-06 13:07:27', 22);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(9, 3, '2024-03-06 13:07:28', '2024-03-06 13:07:28', 23);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(9, 4, '2024-03-06 13:07:29', '2024-03-06 13:07:29', 24);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(11, 1, '2024-03-06 13:07:31', '2024-03-06 13:07:31', 25);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(11, 2, '2024-03-06 13:07:32', '2024-03-06 13:07:32', 26);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(11, 3, '2024-03-06 13:07:32', '2024-03-06 13:07:32', 27);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(11, 4, '2024-03-06 13:07:33', '2024-03-06 13:07:33', 28);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(12, 1, '2024-03-06 13:07:35', '2024-03-06 13:07:35', 29);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(12, 2, '2024-03-06 13:07:35', '2024-03-06 13:07:35', 30);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(12, 3, '2024-03-06 13:07:36', '2024-03-06 13:07:36', 31);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(12, 4, '2024-03-06 13:07:37', '2024-03-06 13:07:37', 32);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(13, 1, '2024-03-06 13:07:38', '2024-03-06 13:07:38', 33);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(13, 2, '2024-03-06 13:07:39', '2024-03-06 13:07:39', 34);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(13, 3, '2024-03-06 13:07:40', '2024-03-06 13:07:40', 35);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(13, 4, '2024-03-06 13:07:41', '2024-03-06 13:07:41', 36);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(13, 6, '2024-03-06 13:07:42', '2024-03-06 13:07:42', 37);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(13, 7, '2024-03-06 13:07:42', '2024-03-06 13:07:42', 38);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(15, 1, '2024-03-06 13:07:45', '2024-03-06 13:07:45', 39);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(15, 3, '2024-03-06 13:07:45', '2024-03-06 13:07:45', 40);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(15, 4, '2024-03-06 13:07:46', '2024-03-06 13:07:46', 41);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(15, 8, '2024-03-06 13:07:47', '2024-03-06 13:07:47', 42);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(16, 1, '2024-03-06 13:07:48', '2024-03-06 13:07:48', 43);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(16, 3, '2024-03-06 13:07:49', '2024-03-06 13:07:49', 44);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(16, 4, '2024-03-06 13:07:50', '2024-03-06 13:07:50', 45);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(18, 1, '2024-03-06 13:07:52', '2024-03-06 13:07:52', 46);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(18, 3, '2024-03-06 13:07:52', '2024-03-06 13:07:52', 47);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(18, 4, '2024-03-06 13:07:53', '2024-03-06 13:07:53', 48);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(19, 1, '2024-03-06 13:07:55', '2024-03-06 13:07:55', 49);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(19, 3, '2024-03-06 13:07:56', '2024-03-06 13:07:56', 50);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(19, 4, '2024-03-06 13:07:57', '2024-03-06 13:07:57', 51);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(21, 1, '2024-03-06 13:07:59', '2024-03-06 13:07:59', 52);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(21, 3, '2024-03-06 13:08:00', '2024-03-06 13:08:00', 53);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(21, 4, '2024-03-06 13:08:00', '2024-03-06 13:08:00', 54);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(22, 1, '2024-03-06 13:08:02', '2024-03-06 13:08:02', 55);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(22, 3, '2024-03-06 13:08:03', '2024-03-06 13:08:03', 56);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(22, 4, '2024-03-06 13:08:03', '2024-03-06 13:08:03', 57);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(23, 1, '2024-03-06 13:08:05', '2024-03-06 13:08:05', 58);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(23, 3, '2024-03-06 13:08:06', '2024-03-06 13:08:06', 59);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(23, 4, '2024-03-06 13:08:07', '2024-03-06 13:08:07', 60);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(24, 1, '2024-03-06 13:08:08', '2024-03-06 13:08:08', 61);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(24, 2, '2024-03-06 13:08:09', '2024-03-06 13:08:09', 62);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(24, 3, '2024-03-06 13:08:10', '2024-03-06 13:08:10', 63);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(24, 4, '2024-03-06 13:08:11', '2024-03-06 13:08:11', 64);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(25, 1, '2024-03-06 13:08:12', '2024-03-06 13:08:12', 65);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(25, 2, '2024-03-06 13:08:13', '2024-03-06 13:08:13', 66);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(25, 3, '2024-03-06 13:08:14', '2024-03-06 13:08:14', 67);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(25, 4, '2024-03-06 13:08:15', '2024-03-06 13:08:15', 68);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(26, 1, '2024-03-06 13:08:16', '2024-03-06 13:08:16', 69);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(26, 2, '2024-03-06 13:08:17', '2024-03-06 13:08:17', 70);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(26, 3, '2024-03-06 13:08:18', '2024-03-06 13:08:18', 71);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(26, 4, '2024-03-06 13:08:19', '2024-03-06 13:08:19', 72);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(27, 1, '2024-03-06 13:08:20', '2024-03-06 13:08:20', 73);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(27, 2, '2024-03-06 13:08:21', '2024-03-06 13:08:21', 74);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(27, 3, '2024-03-06 13:08:22', '2024-03-06 13:08:22', 75);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(27, 4, '2024-03-06 13:08:23', '2024-03-06 13:08:23', 76);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(28, 1, '2024-03-06 13:08:24', '2024-03-06 13:08:24', 77);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(28, 2, '2024-03-06 13:08:25', '2024-03-06 13:08:25', 78);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(28, 3, '2024-03-06 13:08:26', '2024-03-06 13:08:26', 79);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(28, 4, '2024-03-06 13:08:27', '2024-03-06 13:08:27', 80);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(29, 1, '2024-03-06 13:08:28', '2024-03-06 13:08:28', 81);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(29, 2, '2024-03-06 13:08:29', '2024-03-06 13:08:29', 82);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(29, 3, '2024-03-06 13:08:30', '2024-03-06 13:08:30', 83);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(30, 1, '2024-03-06 13:08:31', '2024-03-06 13:08:31', 84);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(31, 1, '2024-03-06 13:08:32', '2024-03-06 13:08:32', 85);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(31, 3, '2024-03-06 13:08:33', '2024-03-06 13:08:33', 86);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(32, 1, '2024-03-06 13:08:35', '2024-03-06 13:08:35', 87);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(32, 2, '2024-03-06 13:08:35', '2024-03-06 13:08:35', 88);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(32, 3, '2024-03-06 13:08:36', '2024-03-06 13:08:36', 89);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(32, 4, '2024-03-06 13:08:37', '2024-03-06 13:08:37', 90);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(33, 1, '2024-03-06 13:08:38', '2024-03-06 13:08:38', 91);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(35, 1, '2024-03-06 13:08:40', '2024-03-06 13:08:40', 92);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(35, 2, '2024-03-06 13:08:41', '2024-03-06 13:08:41', 93);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(35, 3, '2024-03-06 13:08:42', '2024-03-06 13:08:42', 94);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(35, 4, '2024-03-06 13:08:43', '2024-03-06 13:08:43', 95);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(36, 1, '2024-03-06 13:08:44', '2024-03-06 13:08:44', 96);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(36, 2, '2024-03-06 13:08:45', '2024-03-06 13:08:45', 97);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(36, 3, '2024-03-06 13:08:46', '2024-03-06 13:08:46', 98);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(36, 4, '2024-03-06 13:08:46', '2024-03-06 13:08:46', 99);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(37, 1, '2024-03-06 13:08:48', '2024-03-06 13:08:48', 100);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(37, 2, '2024-03-06 13:08:48', '2024-03-06 13:08:48', 101);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(37, 3, '2024-03-06 13:08:49', '2024-03-06 13:08:49', 102);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(37, 4, '2024-03-06 13:08:50', '2024-03-06 13:08:50', 103);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(38, 1, '2024-03-06 13:08:51', '2024-03-06 13:08:51', 104);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(38, 2, '2024-03-06 13:08:52', '2024-03-06 13:08:52', 105);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(38, 3, '2024-03-06 13:08:53', '2024-03-06 13:08:53', 106);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(38, 4, '2024-03-06 13:08:54', '2024-03-06 13:08:54', 107);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(39, 1, '2024-03-06 13:08:55', '2024-03-06 13:08:55', 108);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(39, 2, '2024-03-06 13:08:56', '2024-03-06 13:08:56', 109);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(39, 3, '2024-03-06 13:08:57', '2024-03-06 13:08:57', 110);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(39, 4, '2024-03-06 13:08:58', '2024-03-06 13:08:58', 111);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(40, 1, '2024-03-06 13:08:59', '2024-03-06 13:08:59', 112);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(40, 2, '2024-03-06 13:09:00', '2024-03-06 13:09:00', 113);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(40, 3, '2024-03-06 13:09:01', '2024-03-06 13:09:01', 114);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(40, 4, '2024-03-06 13:09:02', '2024-03-06 13:09:02', 115);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(41, 1, '2024-03-06 13:09:03', '2024-03-06 13:09:03', 116);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(41, 2, '2024-03-06 13:09:04', '2024-03-06 13:09:04', 117);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(41, 3, '2024-03-06 13:09:05', '2024-03-06 13:09:05', 118);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(41, 4, '2024-03-06 13:09:05', '2024-03-06 13:09:05', 119);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(42, 1, '2024-03-06 13:09:07', '2024-03-06 13:09:07', 120);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(42, 2, '2024-03-06 13:09:08', '2024-03-06 13:09:08', 121);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(42, 3, '2024-03-06 13:09:08', '2024-03-06 13:09:08', 122);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(42, 4, '2024-03-06 13:09:09', '2024-03-06 13:09:09', 123);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(43, 1, NULL, NULL, 124);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(44, 1, NULL, NULL, 125);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(45, 1, NULL, NULL, 126);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(12, 5, NULL, NULL, 127);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(11, 5, NULL, NULL, 128);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(18, 9, NULL, NULL, 129);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(21, 11, NULL, NULL, 130);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(19, 10, NULL, NULL, 131);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(22, 12, NULL, NULL, 132);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(46, 1, NULL, NULL, 133);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(46, 2, '2024-03-06 13:09:09', '2024-03-06 13:09:09', 134);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(46, 3, '2024-03-06 13:09:09', '2024-03-06 13:09:09', 135);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(46, 4, '2024-03-06 13:09:09', '2024-03-06 13:09:09', 136);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(49, 1, NULL, NULL, 137);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(49, 2, NULL, NULL, 138);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(49, 3, NULL, NULL, 139);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(49, 4, NULL, NULL, 140);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(50, 1, NULL, NULL, 141);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(50, 2, NULL, NULL, 142);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(50, 3, NULL, NULL, 143);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(50, 4, NULL, NULL, 144);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(16, 13, NULL, NULL, 145);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(58, 1, '2024-03-30 16:56:14', '2024-03-30 16:56:14', 150);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(59, 1, '2024-04-04 08:07:29', '2024-04-04 08:07:29', 151);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(59, 2, '2024-04-04 08:07:29', '2024-04-04 08:07:29', 152);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(59, 3, '2024-04-04 08:07:29', '2024-04-04 08:07:29', 153);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(59, 4, '2024-04-04 08:07:30', '2024-04-04 08:07:30', 154);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(60, 1, '2024-05-16 08:13:28', '2024-05-16 08:13:28', 155);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(60, 2, '2024-05-16 08:13:31', '2024-05-16 08:13:31', 156);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(60, 3, '2024-05-16 08:13:33', '2024-05-16 08:13:33', 157);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(60, 4, '2024-05-16 08:13:35', '2024-05-16 08:13:35', 158);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(61, 1, '2024-06-05 16:44:08', '2024-06-05 16:44:08', 159);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(62, 1, '2024-07-06 15:14:23', '2024-07-06 15:14:23', 160);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(62, 2, '2024-07-06 15:14:23', '2024-07-06 15:14:23', 161);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(62, 3, '2024-07-06 15:14:23', '2024-07-06 15:14:23', 162);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(62, 4, '2024-07-06 15:14:23', '2024-07-06 15:14:23', 163);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(95, 1, '2024-07-18 10:52:30', '2024-07-18 10:52:30', 193);
INSERT INTO demo_winter_erp.public.setting_menu_permissions(menu_id, permission_id, created_at, updated_at, id) VALUES
(96, 1, '2024-07-18 10:53:05', '2024-07-18 10:53:05', 194);