--
-- Script was generated by Devart dbForge Studio for PostgreSQL, Version 3.1.839.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 24/07/2024 10:25:54
-- Server version: 14.10
--

INSERT INTO demo_winter_erp.public.rekening(id, nama_rekening, nama_pemegang, nomor_rekening, created_at, updated_at) VALUES
(1, E'asd', E'nama', E'111', '2024-01-19 07:46:39', '2024-01-19 07:46:39');