--
-- Script was generated by Devart dbForge Studio for PostgreSQL, Version 3.1.839.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 24/07/2024 10:25:57
-- Server version: 14.10
--

INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1617, 4, E'manajemen-produk', false, false, false, false, '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1618, 4, E'bantuan-pelanggan', false, false, false, false, '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1619, 4, E'bantuan-pelanggan-trouble', false, false, false, false, '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1620, 4, E'softsurveys', false, false, false, false, '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1621, 4, E'surveyonsites', false, false, false, false, '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1622, 4, E'instalasi', false, false, false, false, '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1623, 4, E'aktivasi', false, false, false, false, '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1624, 4, E'manajemen-sales-prospek', false, false, false, false, '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1625, 4, E'manajemen-approval', false, false, false, false, '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1626, 4, E'manajemen-wo', false, false, false, false, '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1627, 4, E'manajemen-invoice-pelanggan', false, false, false, false, '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1628, 4, E'manajemen-invoice', false, false, false, false, '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1629, 4, E'data-master', false, false, false, false, '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1630, 4, E'invoice-vendor', false, false, false, false, '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1631, 4, E'manajemen-akun', false, false, false, false, '2024-05-30 15:10:55', '2024-05-30 15:10:55');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1560, 7, E'manajemen-produk', false, false, false, false, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1561, 7, E'bantuan-pelanggan', false, false, false, false, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1562, 7, E'bantuan-pelanggan-trouble', false, false, false, false, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1563, 7, E'softsurveys', false, false, false, false, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1564, 7, E'surveyonsites', false, false, false, false, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1565, 7, E'instalasi', false, false, false, false, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1566, 7, E'aktivasi', false, false, false, false, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1567, 7, E'manajemen-sales-prospek', false, false, false, false, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1568, 7, E'laporan-sales-prospek', false, false, false, false, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1486, 5, E'manajemen-produk', false, false, false, false, '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1487, 5, E'bantuan-pelanggan', false, false, false, false, '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1488, 5, E'bantuan-pelanggan-trouble', false, false, false, false, '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1489, 5, E'softsurveys', false, false, false, false, '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1490, 5, E'surveyonsites', false, false, false, false, '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1491, 5, E'instalasi', false, false, false, false, '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1492, 5, E'aktivasi', false, false, false, false, '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1569, 7, E'manajemen-pelanggan', false, false, false, false, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1570, 7, E'manajemen-berlangganan-pelanggan', false, false, false, false, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1571, 7, E'manajemen-invoice-pelanggan', false, false, false, false, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1572, 7, E'manajemen-invoice', false, false, false, false, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1573, 7, E'data-master', false, false, false, false, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1574, 7, E'manajemen-vendor', false, false, false, false, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1575, 7, E'manajemen-berlangganan-vendor', false, false, false, false, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1576, 7, E'invoice-vendor', false, false, false, false, '2024-05-02 02:42:05', '2024-05-02 02:42:05');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1493, 5, E'manajemen-sales-prospek', false, false, false, false, '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1494, 5, E'manajemen-approval', false, false, false, false, '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1495, 5, E'manajemen-wo', false, false, false, false, '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1496, 5, E'data-master', false, false, false, false, '2024-04-30 10:05:04', '2024-04-30 10:05:04');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1603, 2, E'manajemen-produk', false, false, false, false, '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1604, 2, E'manajemen-sales', false, false, false, false, '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1605, 2, E'bantuan-pelanggan', false, false, false, false, '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1606, 2, E'bantuan-pelanggan-trouble', false, false, false, false, '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1607, 2, E'softsurveys', false, false, false, false, '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1608, 2, E'surveyonsites', false, false, false, false, '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1609, 2, E'instalasi', false, false, false, false, '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1610, 2, E'aktivasi', false, false, false, false, '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1611, 2, E'manajemen-sales-prospek', false, false, false, false, '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1612, 2, E'manajemen-approval', false, false, false, false, '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1613, 2, E'manajemen-wo', false, false, false, false, '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1614, 2, E'manajemen-pelanggan', false, false, false, false, '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1615, 2, E'data-master', false, false, false, false, '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1616, 2, E'manajemen-akun', false, false, false, false, '2024-05-27 15:48:30', '2024-05-27 15:48:30');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1684, 3, E'manajemen-produk', false, false, false, false, '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1685, 3, E'bantuan-pelanggan', false, false, false, false, '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1686, 3, E'bantuan-pelanggan-trouble', false, false, false, false, '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1687, 3, E'softsurveys', false, false, false, false, '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1688, 3, E'surveyonsites', false, false, false, false, '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1689, 3, E'instalasi', false, false, false, false, '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1690, 3, E'aktivasi', false, false, false, false, '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1691, 3, E'manajemen-sales-prospek', false, false, false, false, '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1692, 3, E'manajemen-approval', false, false, false, false, '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1693, 3, E'manajemen-wo', false, false, false, false, '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1694, 3, E'manajemen-pelanggan', false, false, false, false, '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1695, 3, E'manajemen-berlangganan-pelanggan', false, false, false, false, '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1696, 3, E'data-master', false, false, false, false, '2024-06-07 14:39:28', '2024-06-07 14:39:28');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1705, 77, E'manajemen-produk', false, false, false, false, '2024-06-20 09:17:36', '2024-06-20 09:17:36');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1706, 77, E'manajemen-sales', false, false, false, false, '2024-06-20 09:17:36', '2024-06-20 09:17:36');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1707, 77, E'bantuan-pelanggan', false, false, false, false, '2024-06-20 09:17:36', '2024-06-20 09:17:36');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1708, 77, E'bantuan-pelanggan-trouble', false, false, false, false, '2024-06-20 09:17:36', '2024-06-20 09:17:36');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1709, 77, E'softsurveys', false, false, false, false, '2024-06-20 09:17:36', '2024-06-20 09:17:36');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1710, 77, E'surveyonsites', false, false, false, false, '2024-06-20 09:17:36', '2024-06-20 09:17:36');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1711, 77, E'instalasi', false, false, false, false, '2024-06-20 09:17:36', '2024-06-20 09:17:36');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1712, 77, E'manajemen-sales-prospek', false, false, false, false, '2024-06-20 09:17:36', '2024-06-20 09:17:36');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1713, 77, E'manajemen-approval', false, false, false, false, '2024-06-20 09:17:36', '2024-06-20 09:17:36');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1714, 77, E'data-master', false, false, false, false, '2024-06-20 09:17:36', '2024-06-20 09:17:36');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1738, 41, E'manajemen-produk', false, false, false, false, '2024-07-18 10:54:35', '2024-07-18 10:54:35');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1739, 41, E'manajemen-sales', false, false, false, false, '2024-07-18 10:54:35', '2024-07-18 10:54:35');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1740, 41, E'bantuan-pelanggan', false, false, false, false, '2024-07-18 10:54:35', '2024-07-18 10:54:35');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1741, 41, E'bantuan-pelanggan-trouble', false, false, false, false, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1742, 41, E'softsurveys', false, false, false, false, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1743, 41, E'surveyonsites', false, false, false, false, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1744, 41, E'instalasi', false, false, false, false, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1745, 41, E'aktivasi', false, false, false, false, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1746, 41, E'manajemen-sales-prospek', false, false, false, false, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1747, 41, E'manajemen-approval', false, false, false, false, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1748, 41, E'penawaran', false, false, false, false, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1749, 41, E'manajemen-user', false, false, false, false, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1750, 41, E'manajemen-role', false, false, false, false, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1751, 41, E'manajemen-user-logs', false, false, false, false, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1752, 41, E'manajemen-wo', false, false, false, false, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1753, 41, E'laporan-sales-prospek', false, false, false, false, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1754, 41, E'laporan-pelanggan', false, false, false, false, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1755, 41, E'laporan-sales', false, false, false, false, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1756, 41, E'laporan-ticket', false, false, false, false, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1757, 41, E'manajemen-pelanggan', false, false, false, false, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1758, 41, E'manajemen-berlangganan-pelanggan', false, false, false, false, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1759, 41, E'manajemen-invoice-pelanggan', false, false, false, false, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1760, 41, E'manajemen-invoice', false, false, false, false, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1761, 41, E'data-master', false, false, false, false, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1762, 41, E'manajemen-vendor', false, false, false, false, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1763, 41, E'manajemen-berlangganan-vendor', false, false, false, false, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1764, 41, E'invoice-vendor', false, false, false, false, '2024-07-18 10:54:36', '2024-07-18 10:54:36');
INSERT INTO demo_winter_erp.public.role_permissions(id, role_id, slug_menu, read, "create", update, delete, created_at, updated_at) VALUES
(1765, 41, E'manajemen-akun', false, false, false, false, '2024-07-18 10:54:36', '2024-07-18 10:54:36');