--
-- Script was generated by Devart dbForge Studio for PostgreSQL, Version 3.1.839.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 24/07/2024 10:25:36
-- Server version: 14.10
--

INSERT INTO demo_winter_erp.public.jadwal_instalasi(id, sales_prospek_id, survey_onsite_id, tanggal, lokasi_id, catatan, created_at, updated_at, uid) VALUES
(127, 274, 208, '22/07/2024 21:43:00.000000+07 AD', E'Sesuai', NULL, '2024-07-22 21:44:04', '2024-07-22 21:44:04', E'admin.erp');
INSERT INTO demo_winter_erp.public.jadwal_instalasi(id, sales_prospek_id, survey_onsite_id, tanggal, lokasi_id, catatan, created_at, updated_at, uid) VALUES
(128, 272, 209, '25/07/2024 09:25:00.000000+07 AD', E'sesuai', E'laksanakan', '2024-07-23 05:25:52', '2024-07-23 05:25:52', E'maurizka');
INSERT INTO demo_winter_erp.public.jadwal_instalasi(id, sales_prospek_id, survey_onsite_id, tanggal, lokasi_id, catatan, created_at, updated_at, uid) VALUES
(129, 273, 210, '24/07/2024 09:20:00.000000+07 AD', E'sesuai', E'laksanakan', '2024-07-23 05:58:58', '2024-07-23 05:58:58', E'maurizka');
INSERT INTO demo_winter_erp.public.jadwal_instalasi(id, sales_prospek_id, survey_onsite_id, tanggal, lokasi_id, catatan, created_at, updated_at, uid) VALUES
(130, 271, 207, '23/07/2024 06:27:00.000000+07 AD', E'a', NULL, '2024-07-23 06:27:19', '2024-07-23 06:27:19', E'admin.erp');