--
-- Script was generated by Devart dbForge Studio for PostgreSQL, Version 3.1.839.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 24/07/2024 10:25:37
-- Server version: 14.10
--

INSERT INTO demo_winter_erp.public.jenis_prospeks(id, subjek) VALUES
(1, E'Penawaran Internet Dedicated');
INSERT INTO demo_winter_erp.public.jenis_prospeks(id, subjek) VALUES
(2, E'Penawaran Internet Personal');
INSERT INTO demo_winter_erp.public.jenis_prospeks(id, subjek) VALUES
(3, E'Penawaran Internet Broadband');
INSERT INTO demo_winter_erp.public.jenis_prospeks(id, subjek) VALUES
(4, E'Penawaran Co-location');
INSERT INTO demo_winter_erp.public.jenis_prospeks(id, subjek) VALUES
(5, E'Penawaran Paket Sekolah');
INSERT INTO demo_winter_erp.public.jenis_prospeks(id, subjek) VALUES
(6, E'Penawaran Paket Hotel');
INSERT INTO demo_winter_erp.public.jenis_prospeks(id, subjek) VALUES
(7, E'Penawaran Aplikasi');
INSERT INTO demo_winter_erp.public.jenis_prospeks(id, subjek) VALUES
(8, E'Penawaran Digital Signage');
INSERT INTO demo_winter_erp.public.jenis_prospeks(id, subjek) VALUES
(9, E'Penawaran Project');
INSERT INTO demo_winter_erp.public.jenis_prospeks(id, subjek) VALUES
(10, E'Penawaran VPN');
INSERT INTO demo_winter_erp.public.jenis_prospeks(id, subjek) VALUES
(11, E'Penawaran Virtual Private Server ( VPS )');
INSERT INTO demo_winter_erp.public.jenis_prospeks(id, subjek) VALUES
(12, E'Penawaran Fiber Optik');
INSERT INTO demo_winter_erp.public.jenis_prospeks(id, subjek) VALUES
(13, E'Penawaran Managed Service');
INSERT INTO demo_winter_erp.public.jenis_prospeks(id, subjek) VALUES
(14, E'Penawaran Hosting');
INSERT INTO demo_winter_erp.public.jenis_prospeks(id, subjek) VALUES
(15, E'Penawaran Local Loop');