--
-- Script was generated by Devart dbForge Studio for PostgreSQL, Version 3.1.839.0
-- Product home page: http://www.devart.com/dbforge/postgresql/studio
-- Script date 24/07/2024 10:25:32
-- Server version: 14.10
--

INSERT INTO demo_winter_erp.public.bandwidth(id, nama, created_at, updated_at, nama_tenant) VALUES
(2, E'10', '2024-01-23 03:40:56', '2024-01-23 03:40:56', E'SMY');
INSERT INTO demo_winter_erp.public.bandwidth(id, nama, created_at, updated_at, nama_tenant) VALUES
(3, E'20', '2024-01-23 03:41:00', '2024-01-23 03:41:00', E'SMY');
INSERT INTO demo_winter_erp.public.bandwidth(id, nama, created_at, updated_at, nama_tenant) VALUES
(1, E'30', '2024-01-22 04:07:07', '2024-01-24 09:27:28', E'SMY');
INSERT INTO demo_winter_erp.public.bandwidth(id, nama, created_at, updated_at, nama_tenant) VALUES
(6, E'50', '2024-02-02 03:39:07', '2024-02-02 03:39:14', E'SMY');
INSERT INTO demo_winter_erp.public.bandwidth(id, nama, created_at, updated_at, nama_tenant) VALUES
(40, E'60', '2024-02-06 04:00:39', '2024-02-06 04:01:45', E'SMY');
INSERT INTO demo_winter_erp.public.bandwidth(id, nama, created_at, updated_at, nama_tenant) VALUES
(73, E'100', '2024-02-23 01:51:38', '2024-02-23 01:51:38', E'SMY');
INSERT INTO demo_winter_erp.public.bandwidth(id, nama, created_at, updated_at, nama_tenant) VALUES
(77, E'300', '2024-06-11 13:15:43', '2024-06-11 13:15:43', E'WA');
INSERT INTO demo_winter_erp.public.bandwidth(id, nama, created_at, updated_at, nama_tenant) VALUES
(5, E'40', '2024-01-24 09:19:03', '2024-06-11 13:18:58', E'WA');
INSERT INTO demo_winter_erp.public.bandwidth(id, nama, created_at, updated_at, nama_tenant) VALUES
(78, E'200', '2024-06-11 14:02:21', '2024-06-12 11:50:47', E'WA');
INSERT INTO demo_winter_erp.public.bandwidth(id, nama, created_at, updated_at, nama_tenant) VALUES
(91, E'150', '2024-06-12 14:09:56', '2024-06-12 15:19:25', E'SMY');